/**
*	Loading Variables: SPR Display
*	Jonathan Vitale
*	Changes:
*
*	Version 0.5:
*		- Uses variables for if statements
*		- Format: By sheet, Visualziation
*
*	Reminder:
*	THIS FILE IS THE RAW QLIK CODE. IT **MUST** BE COMPILED INTO STRINGS TO BE LOADED INTO A SCRIPT.
*   Make sure to save the formatted code in a separate file and keep this file raw. 
*	For SUBLIME TEXT use the RegReplace package with custom rules and commands
*   Note: I am using the RegEx instead of the default py regualar expression engine (v.1). Set this in package settings.
*	Also, instead of using single quotes for final strings, use ` to avoid unnecessary replacements
**/

///// Universal Variables
	//// Expressions

		let vExpr_AllDomainsPossible = GetPossibleCount([Domain Name]) > 1 and GetSelectedCount([Domain Name]) = 0 or WildMatch(Concat(GetFieldSelections([Domain Name])), '*Overall*') > 0 or WildMatch(Concat(GetFieldSelections([Metric Name])), '*Overall Score*') > 0;
		let vExpr_MultipleDomainsSelected = GetSelectedCount([Domain Name]) > 1 and WildMatch(Concat(GetFieldSelections([Domain Name])), '*Overall*') < 1 and WildMatch(Concat(GetFieldSelections([Metric Name])), '*Overall Score*') < 1;
		let vExpr_MultipleMetricsSelected = GetSelectedCount([Metric Name]) > 1 and WildMatch(Concat(GetFieldSelections([Domain Name])), '*Overall*') < 1 and WildMatch(Concat(GetFieldSelections([Metric Name])), '*Overall Score*') < 1;
		let vExpr_SomeDomainsSelected = GetSelectedCount([Domain Name]) > 0 and WildMatch(Concat(GetFieldSelections([Domain Name])), '*Overall*') < 1 and WildMatch(Concat(GetFieldSelections([Metric Name])), '*Overall Score*') < 1;
		let vExpr_SingleDomainSelected = WildMatch(Concat(GetFieldSelections([Domain Name])), '*Overall*') < 1 and WildMatch(Concat(GetFieldSelections([Metric Name])), '*Overall Score*') < 1 and (GetSelectedCount([Domain Name]) = 1 or (GetPossibleCount([Domain Name]) = 0 and WildMatch(Concat(GetFieldSelections([Metric Name])), '*Domain Score*') > 0));
		let vExpr_SingleDomainSelected_AllMetricsPossible  = $(vExpr_SingleDomainSelected) and GetSelectedCount([Metric Name]) = 0;
		let vExpr_SingleDomainPossible_SomeMetricsSelected = $(vExpr_SingleDomainSelected) and GetSelectedCount([Metric Name]) > 0;
		let vExpr_MultipleDomainsPossible = WildMatch(Concat(GetFieldSelections([Domain Name])), '*Overall*') < 1 and WildMatch(Concat(GetFieldSelections([Metric Name])), '*Overall Score*') < 1 and GetPossibleCount([Domain Name]) > 1;
		let vExpr_MultipleDomainsPossible_AllMetricsPossible = $(vExpr_MultipleDomainsPossible) and GetSelectedCount([Metric Name]) = 0;
		let vExpr_MultipleDomainsPossible_SomeMetricsSelected = $(vExpr_MultipleDomainsPossible) and GetSelectedCount([Metric Name]) > 0 and WildMatch(Concat(GetFieldSelections([Metric Name])), '*Domain Score*') < 1;
		let vExpr_SomeMetricsSelected = GetSelectedCount([Metric Name]) > 0 and GetPossibleCount([Domain Name]) = 1 and WildMatch(Concat(GetFieldSelections([Metric Name])), '*Domain Score*') < 1;
		let vExpr_SingleMetricSelected = GetSelectedCount([Metric Name]) = 1 and GetPossibleCount([Domain Name]) = 1 and WildMatch(Concat(GetFieldSelections([Metric Name])), '*Domain Score*') < 1;
		let vExpr_NoMetricSelected = GetSelectedCount([Metric Name]) = 0 or WildMatch(Concat(GetFieldSelections([Metric Name])), '*Domain Score*') > 0;
		let vExpr_SingleDomainSelected_or_SingleMetricSelected = $(vExpr_SingleDomainSelected) or $(vExpr_SingleMetricSelected);

	//// Date
		 let v_Max_YearEnd = Num#(Max(YearEnd));
		 let v_Last_YearEnd = Num#(Max(YearEnd)-1);
		 let v_LastLast_YearEnd = Num#(Max(YearEnd)-2);
		 let v_LastLastLast_YearEnd = Num#(Max(YearEnd)-3);
		 let v_Max_Year = (max(left(Year,4))) & '-' & (max(right(Year,4)));
		 let v_Last_Year = (max(left(Year,4))-1) & '-' & (max(right(Year,4))-1);
		 let v_LastLast_Year = (max(left(Year,4))-2) & '-' & (max(right(Year,4))-2);
		 let v_LastLastLast_Year = (max(left(Year,4))-3) & '-' & (max(right(Year,4))-3);

	//// Count of schools, students
		let vMM_Count_Reports = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Count(distinct {<[Points Possible Overall] = {">0"}, [Overall Tier] = {"*"}>}%SchoolReportYearKey),
			    IF ($(vExpr_SomeDomainsSelected), 
			    	Count(distinct {<[Points Possible in Domain] = {">0"}, [Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}>}%SchoolReportYearKey),
			        IF ($(vExpr_SomeMetricsSelected), 
			          Count(distinct {<[Points Possible for Metric] = {">0"}, [Tier for Metric] = {"*"}>}%SchoolReportYearKey),
			        )
			    )
			)
			, '#,##0');
		// The number of schools in the most recent year.
		let vMM_Count_Reports_Current = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Count(distinct {<[Points Possible Overall] = {">0"}, [Overall Tier] = {"*"}, YearEnd={$(=$(v_Max_YearEnd))}>}%SchoolReportYearKey),
			    IF ($(vExpr_SomeDomainsSelected), 
			    	Count(distinct {<[Points Possible in Domain] = {">0"}, [Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>}%SchoolReportYearKey),
			        IF ($(vExpr_SomeMetricsSelected), 
			          Count(distinct {<[Points Possible for Metric] = {">0"}, [Tier for Metric] = {"*"}, YearEnd={$(=$(v_Max_YearEnd))}>}%SchoolReportYearKey),
			        )
			    )
			)
			, '#,##0');
		let vLab_Count_Reports_Current = '# of School Reports (' & $(v_Max_Year) & ')';
		
		// The number of schools in the previous year.
		let vMM_Count_Reports_Previous = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Count(distinct {<[Points Possible Overall] = {">0"}, [Overall Tier] = {"*"}, YearEnd={$(=$(v_Last_YearEnd))}>}%SchoolReportYearKey),
			    IF ($(vExpr_SomeDomainsSelected), 
			    	Count(distinct {<[Points Possible in Domain] = {">0"}, [Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>}%SchoolReportYearKey),
			        IF ($(vExpr_SomeMetricsSelected), 
			          Count(distinct {<[Points Possible for Metric] = {">0"}, [Tier for Metric] = {"*"}, YearEnd={$(=$(v_Last_YearEnd))}>}%SchoolReportYearKey),
			        )
			    )
			)
			, '#,##0');
		let vLab_Count_Reports_Previous = '# of School Reports (' & $(v_Last_Year) & ')';

		let vMM_Count_Reports_Previous2 = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Count(distinct {<[Points Possible Overall] = {">0"}, [Overall Tier] = {"*"}, YearEnd={$(=$(v_LastLast_YearEnd))}>}%SchoolReportYearKey),
			    IF ($(vExpr_SomeDomainsSelected), 
			    	Count(distinct {<[Points Possible in Domain] = {">0"}, [Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_LastLast_YearEnd))}>}%SchoolReportYearKey),
			        IF ($(vExpr_SomeMetricsSelected), 
			          Count(distinct {<[Points Possible for Metric] = {">0"}, [Tier for Metric] = {"*"}, YearEnd={$(=$(v_LastLast_YearEnd))}>}%SchoolReportYearKey),
			        )
			    )
			)
			, '#,##0');
		// The number of schools in the previous three years.
		let vMM_Count_Reports_3Year_Current = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Count(distinct {<[Points Possible Overall] = {">0"}, [Overall Tier] = {"*"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearKey),
			    IF ($(vExpr_SomeDomainsSelected), 
			    	Count(distinct {<[Points Possible in Domain] = {">0"}, [Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearKey),
			        IF ($(vExpr_SomeMetricsSelected), 
			          Count(distinct {<[Points Possible for Metric] = {">0"}, [Tier for Metric] = {"*"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearKey),
			        )
			    )
			)
			, '#,##0');
		let vLab_Count_Reports_3Year_Current = '# of School Reports (3 Years)';

		let vMM_Count_Reports_ModelReinforce = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Count(distinct {<[Overall Tier] = {"Model", "Reinforce"}>}%SchoolReportYearKey),
			    IF ($(vExpr_SomeDomainsSelected), 
			    	Count(distinct {<[Tier in Domain] = {"Model", "Reinforce"}>}%SchoolReportYearKey),
			        IF ($(vExpr_SomeMetricsSelected), 
			          Count(distinct {<[Tier for Metric] = {"Model", "Reinforce"}>}%SchoolReportYearKey),
			        )
			    )
			)
			, '#,##0');
		let vMM_Count_Reports_ModelReinforce_Current = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Count(distinct {<[Overall Tier] = {"Model", "Reinforce"}, YearEnd={$(=$(v_Max_YearEnd))}>}%SchoolReportYearKey),
			    IF ($(vExpr_SomeDomainsSelected), 
			    	Count(distinct {<[Tier in Domain] = {"Model", "Reinforce"}, YearEnd={$(=$(v_Max_YearEnd))}>}%SchoolReportYearKey),
			        IF ($(vExpr_SomeMetricsSelected), 
			          Count(distinct {<[Tier for Metric] = {"Model", "Reinforce"}, YearEnd={$(=$(v_Max_YearEnd))}>}%SchoolReportYearKey),
			        )
			    )
			)
			, '#,##0');
		let vMM_Count_Reports_ModelReinforce_Previous = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Count(distinct {<[Overall Tier] = {"Model", "Reinforce"}, YearEnd={$(=$(v_Last_YearEnd))}>}%SchoolReportYearKey),
			    IF ($(vExpr_SomeDomainsSelected), 
			    	Count(distinct {<[Tier in Domain] = {"Model", "Reinforce"}, YearEnd={$(=$(v_Last_YearEnd))}>}%SchoolReportYearKey),
			        IF ($(vExpr_SomeMetricsSelected), 
			          Count(distinct {<[Tier for Metric] = {"Model", "Reinforce"}, YearEnd={$(=$(v_Last_YearEnd))}>}%SchoolReportYearKey),
			        )
			    )
			)
			, '#,##0');
		let vMM_Count_Reports_ModelReinforce_YOY = Num(
			$(vMM_Count_Reports_ModelReinforce_Current)-$(vMM_Count_Reports_ModelReinforce_Previous)
			, '#,##0');
		let vMM_Count_Reports_WatchIntervene_Current = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Count(distinct {<[Overall Tier] = {"Watch", "Intervene"}, YearEnd={$(=$(v_Max_YearEnd))}>}%SchoolReportYearKey),
			    IF ($(vExpr_SomeDomainsSelected), 
			    	Count(distinct {<[Tier in Domain] = {"Watch", "Intervene"}, YearEnd={$(=$(v_Max_YearEnd))}>}%SchoolReportYearKey),
			        IF ($(vExpr_SomeMetricsSelected), 
			          Count(distinct {<[Tier for Metric] = {"Watch", "Intervene"}, YearEnd={$(=$(v_Max_YearEnd))}>}%SchoolReportYearKey),
			        )
			    )
			)
			, '#,##0');
		let vMM_Count_Reports_WatchIntervene_Previous = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Count(distinct {<[Overall Tier] = {"Watch", "Intervene"}, YearEnd={$(=$(v_Last_YearEnd))}>}%SchoolReportYearKey),
			    IF ($(vExpr_SomeDomainsSelected), 
			    	Count(distinct {<[Tier in Domain] = {"Watch", "Intervene"}, YearEnd={$(=$(v_Last_YearEnd))}>}%SchoolReportYearKey),
			        IF ($(vExpr_SomeMetricsSelected), 
			          Count(distinct {<[Tier for Metric] = {"Watch", "Intervene"}, YearEnd={$(=$(v_Last_YearEnd))}>}%SchoolReportYearKey),
			        )
			    )
			)
			, '#,##0');
		

		let vMM_Count_Students = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Sum({<[Overall Tier] = {"*"}>}Enrollment),
			    IF ($(vExpr_SingleDomainSelected), 
			    	Sum({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}>}Enrollment),
			        IF ($(vExpr_SingleMetricSelected), 
			          Sum({<[Tier for Metric] = {"*"}>}Enrollment),
			        )
			    )
			)
			, '#,##0');

		// The number of students in the most recent year.
		let vMM_Count_Students_Current = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Sum({<[Overall Tier] = {"*"}, YearEnd={$(=$(v_Max_YearEnd))}>}Enrollment),
			    IF ($(vExpr_SingleDomainSelected), 
			    	Sum({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>}Enrollment),
			        IF ($(vExpr_SingleMetricSelected), 
			          Sum({<[Tier for Metric] = {"*"}, YearEnd={$(=$(v_Max_YearEnd))}>}Enrollment),
			        )
			    )
			)
			, '#,##0');
		let vLab_Count_Students_Current = '# of Students (' & $(v_Max_Year) & ')';

		// The number of students in the previous year.
		let vMM_Count_Students_Previous = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Sum({<[Overall Tier] = {"*"}, YearEnd={$(=$(v_Last_YearEnd))}>}Enrollment),
			    IF ($(vExpr_SingleDomainSelected), 
			    	Sum({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>}Enrollment),
			        IF ($(vExpr_SingleMetricSelected), 
			          Sum({<[Tier for Metric] = {"*"}, YearEnd={$(=$(v_Last_YearEnd))}>}Enrollment),
			        )
			    )
			)
			, '#,##0');
		let vLab_Count_Students_Previous = '# of Students (' & $(v_Last_Year) & ')';

		let vMM_Count_Students_ModelReinforce = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Sum({<[Overall Tier] = {"Model", "Reinforce"}>}Enrollment),
			    IF ($(vExpr_SingleDomainSelected), 
			    	Sum({<[Tier in Domain] = {"Model", "Reinforce"}>}Enrollment),
			        IF ($(vExpr_SingleMetricSelected), 
			          Sum({<[Tier for Metric] = {"Model", "Reinforce"}>}Enrollment),
			        )
			    )
			)
			, '#,##0');
		let vMM_Count_Students_ModelReinforce_Current = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Sum({<[Overall Tier] = {"Model", "Reinforce"}, YearEnd={$(=$(v_Max_YearEnd))}>}Enrollment),
			    IF ($(vExpr_SingleDomainSelected), 
			    	Sum({<[Tier in Domain] = {"Model", "Reinforce"}, YearEnd={$(=$(v_Max_YearEnd))}>}Enrollment),
			        IF ($(vExpr_SingleMetricSelected), 
			          Sum({<[Tier for Metric] = {"Model", "Reinforce"}, YearEnd={$(=$(v_Max_YearEnd))}>}Enrollment),
			        )
			    )
			)
			, '#,##0');
		let vMM_Count_Students_ModelReinforce_Previous = Num(
			IF ($(vExpr_AllDomainsPossible), 
				Sum({<[Overall Tier] = {"Model", "Reinforce"}, YearEnd={$(=$(v_Last_YearEnd))}>}Enrollment),
			    IF ($(vExpr_SingleDomainSelected), 
			    	Sum({<[Tier in Domain] = {"Model", "Reinforce"}, YearEnd={$(=$(v_Last_YearEnd))}>}Enrollment),
			        IF ($(vExpr_SingleMetricSelected), 
			          Sum({<[Tier for Metric] = {"Model", "Reinforce"}, YearEnd={$(=$(v_Last_YearEnd))}>}Enrollment),
			        )
			    )
			)
			, '#,##0');
		let vMM_Count_Students_ModelReinforce_YOY = Num(
			$(vMM_Count_Students_ModelReinforce_Current)-$(vMM_Count_Students_ModelReinforce_Previous)
			, '#,##0');

	//// Titles and labels
		let vTitle_Avg_PercScore_OverallToDomainToMetric = 
			IF($(vExpr_SingleDomainSelected_or_SingleMetricSelected),
		    	IF($(vExpr_SingleDomainSelected_AllMetricsPossible), 'Average Score for ' & Only(GetFieldSelections([Domain Name])),
		        IF($(vExpr_MultipleDomainsPossible_AllMetricsPossible), 'Average Score for Available Domains',
		        IF($(vExpr_MultipleMetricsSelected), 'Average Score for Selected Metrics',
                IF($(vExpr_SingleMetricSelected), 'Average Score in ' & Only(GetFieldSelections([Metric Name]))
		        )))),
				'Average Overall Score'
	    	);

		let vTitle_Avg_Tier_OverallToDomainToMetric = 
			IF($(vExpr_SingleDomainSelected_or_SingleMetricSelected),
		    	IF($(vExpr_SingleDomainSelected_AllMetricsPossible), 'Tier for ' & Only(GetFieldSelections([Domain Name])),
		        IF($(vExpr_MultipleDomainsPossible_AllMetricsPossible), 'Tier for Available Domains',
		        IF($(vExpr_MultipleMetricsSelected), 'Tier for Selected Metrics',
                IF($(vExpr_SingleMetricSelected), 'Tier in ' & Only(GetFieldSelections([Metric Name]))
		        )))),
				'Overall Tier'
	    	);

	
///// Universal Dimensions and Sorts
	let vDim_DomainToMetric = IF($(vExpr_SingleDomainSelected),
		IF(GetFieldSelections([Domain Name]) = [Domain Name],
			[Metric Name],
	        Null()
	    ),
	    [Domain Name]
	);

	let vSort_PeerGroup = 
		If (WildMatch([Peer Group]y6, '*-*') > 0, 
		  If (WildMatch([Peer Group], 'ES*') > 0, Num#(Right([Peer Group], 1)),
		    If (WildMatch([Peer Group], 'K8*') > 0, 5 + Num#(Right([Peer Group], 1)), 
		    If (WildMatch([Peer Group], 'MS*') > 0, 14 + Num#(Right([Peer Group], 1)), 
		    If (WildMatch([Peer Group], 'HS*') > 0,  17 + Num#(Right([Peer Group], 1)))))),
		 23 + Match([Peer Group], 'ES', 'K8', 'MS', 'HS')   
		);

	//// Calculation Condition
		/// 
			let vCalc_ZeroOrOne_Domains_Metrics = If($(vExpr_AllDomainsPossible) or $(vExpr_SingleDomainSelected_AllMetricsPossible) or $(vExpr_SingleMetricSelected), 1, 0);

			let vCalcDisplay_ZeroOrOne_Domains_Metrics = 
				If($(vExpr_MultipleDomainsSelected), 'You have multiple domains selected. Please select only one.',
					If($(vExpr_MultipleMetricsSelected), 'You have multiple metrics selected. Please select only one.',
				));


///// Landing Page

	

	//// KPI (top-left): Avg Score - drill from overall to selected domain/metric

		/// Title
			// vTitle_Avg_PercScore_OverallToDomainToMetric

		/// SubTitle
			let vSubTitle_Avg_PercScore_OverallToDomainToMetric = '# of reports: ' & $(vMM_Count_Reports_Current) & ' (' & $(v_Max_Year) & '), ' & $(vMM_Count_Reports_Previous) & ' (' & $(v_Last_Year) & ')';

		/// Measure 1: Average Score in the Current Year (drill from overall to selected domain to selected metric)
			// Description:
			// SPR Score for the current year. If multiple metrics are selected, this is equal to overall score. If a selection on Domain is made and there are no selections on metric, this is equal to the score for the domain. If a single metric is selected, this is equal to the metric score.
			let vMM_Avg_PercScore_OverallToDomainToMetric_Current = Num(
				IF ($(vExpr_AllDomainsPossible),
					Avg({<YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned Overall]),
				    IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
				    	Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned in Domain]),
				        IF ($(vExpr_SingleMetricSelected),
				        	Avg({<YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned for Metric]),
				            Avg(Aggr(If(Count({<[Points Possible for Metric]={""}, YearEnd={$(=$(v_Max_YearEnd))}>}%SchoolReportYearKey) = 0, Sum({<YearEnd={$(=$(v_Max_YearEnd))}>}[Points Earned for Metric]) / Sum({<YearEnd={$(=$(v_Max_YearEnd))}>}[Points Possible for Metric])), [%SchoolReportYearKey]))
				        )
				    )
				)
				, '#0%');

			let vLab_Avg_PercScore_OverallToDomainToMetric_Current = $(vTitle_Avg_PercScore_OverallToDomainToMetric) & ' (' & $(v_Max_Year) &')';

		/// Measure 2: YOY 
			// Average SPR Score in the previous year. If multiple metrics are selected, this is equal to overall score. If a selection on Domain is made and there are no selections on metric, this is equal to the score for the domain. If a single metric is selected, this is equal to the metric score.
			let vMM_Avg_PercScore_OverallToDomainToMetric_Previous = Num(
				IF ($(vExpr_AllDomainsPossible),
					Avg({<YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned Overall]),
				    IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
				    	Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned in Domain]),
				        IF ($(vExpr_SingleMetricSelected),
				        	Avg({<YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned for Metric]),
				            Avg(Aggr(Sum({<YearEnd={$(=$(v_Last_YearEnd))}>}[Points Earned for Metric]) / Sum({<YearEnd={$(=$(v_Last_YearEnd))}>}[Points Possible for Metric]), [%SchoolReportYearKey]))
				        )
				    )
				)
				, '#0%');

			let vLab_Avg_PercScore_OverallToDomainToMetric_Previous = $(vTitle_Avg_PercScore_OverallToDomainToMetric) & ' ('& $(v_Last_Year) &')';	

			// Change in SPR Score from the previous year to the current year. If multiple metrics are selected, this is equal to overall score. If a selection on Domain is made and there are no selections on metric, this is equal to the score for the domain. If a single metric is selected, this is equal to the metric score.
			let vMM_Avg_PercScore_OverallToDomainToMetric_YOY = Num(
				Round($(vMM_Avg_PercScore_OverallToDomainToMetric_Current) - $(vMM_Avg_PercScore_OverallToDomainToMetric_Previous), 0.01)
				, '#0%');

			let vLab_Avg_PercScore_OverallToDomainToMetric_YOY = 'YOY: ' & $(vTitle_Avg_PercScore_OverallToDomainToMetric);	

	//// KPI (top-left-middle): 3 Year Runniing Average Score - drill from overall to selected domain/metric
		/// Title
			let vTitle_Avg_PercScore_OverallToDomainToMetric_3Year_Current = '3 Year ' & $(vTitle_Avg_PercScore_OverallToDomainToMetric);

		/// SubTitle
			let vSubTitle_Avg_PercScore_OverallToDomainToMetric_3Year_Current = 'Most recent 3 years: '& $(v_Max_Year) &', ' & $(v_Last_Year) & ', ' & $(v_LastLast_Year);

		/// Measure 1:
			// The average percent of possible points earned in the most recent three years. If multiple metrics are selected, this is equal to overall score. If a selection on Domain is made and there are no selections on metric, this is equal to the score for the domain. If a single metric is selected, this is equal to the metric score.
			let vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Current = Num(
				IF ($(vExpr_AllDomainsPossible),
					RangeAvg(
			           	Avg({<YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned Overall]) ,
			           	Avg({<YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned Overall]) ,
			           	Avg({<YearEnd={$(=$(v_LastLast_YearEnd))}>}[Percent Earned Overall]) 
			        ),
				    IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
				    	RangeAvg(
			              	Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned in Domain]) ,
			              	Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned in Domain]) ,
			              	Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_LastLast_YearEnd))}>}[Percent Earned in Domain]) 
			          	),
				        IF ($(vExpr_SingleMetricSelected),
				        	RangeAvg(
				              	Avg({<YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned for Metric]) ,
				              	Avg({<YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned for Metric]) ,
				              	Avg({<YearEnd={$(=$(v_LastLast_YearEnd))}>}[Percent Earned for Metric]) 
				          	  ),
				            RangeAvg(
				              	Avg(Aggr(Sum({<YearEnd={$(=$(v_Max_YearEnd))}>}[Points Earned for Metric]) / Sum({<YearEnd={$(=$(v_Max_YearEnd))}>}[Points Possible for Metric]), [%SchoolReportYearKey])),
				              	Avg(Aggr(Sum({<YearEnd={$(=$(v_Last_YearEnd))}>}[Points Earned for Metric]) / Sum({<YearEnd={$(=$(v_Last_YearEnd))}>}[Points Possible for Metric]), [%SchoolReportYearKey])),
				              	Avg(Aggr(Sum({<YearEnd={$(=$(v_LastLast_YearEnd))}>}[Points Earned for Metric]) / Sum({<YearEnd={$(=$(v_LastLast_YearEnd))}>}[Points Possible for Metric]), [%SchoolReportYearKey]))
				            )
				        )
				    )
				)
				+ 0.0001, '#0.#%');


			let vLab_Avg_PercScore_OverallToDomainToMetric_3Year_Current = $(vTitle_Avg_PercScore_OverallToDomainToMetric_3Year_Current) & ' (up to '& $(v_Max_Year) &')';
		
		/// Measure 1:
			// The average percent of possible points earned in the most recent three years prior to the current year. If multiple metrics are selected, this is equal to overall score. If a selection on Domain is made and there are no selections on metric, this is equal to the score for the domain. If a single metric is selected, this is equal to the metric score.
			let vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Previous = Num(
				IF ($(vExpr_AllDomainsPossible),
					RangeAvg(
			           	Avg({<YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned Overall]) ,
			           	Avg({<YearEnd={$(=$(v_LastLast_YearEnd))}>}[Percent Earned Overall]) ,
			           	Avg({<YearEnd={$(=$(v_LastLastLast_YearEnd))}>}[Percent Earned Overall]) 
			        ),
				    IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
				    	RangeAvg(
			              	Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned in Domain]) ,
			              	Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_LastLast_YearEnd))}>}[Percent Earned in Domain]) ,
			              	Avg({<YearEnd={$(=$(v_LastLastLast_YearEnd))}>}[Percent Earned in Domain]) 
			          	),
				        IF ($(vExpr_SingleMetricSelected),
				        	RangeAvg(
				              	Avg({<YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned for Metric]) ,
				              	Avg({<YearEnd={$(=$(v_LastLast_YearEnd))}>}[Percent Earned for Metric]) ,
				              	Avg({<YearEnd={$(=$(v_LastLastLast_YearEnd))}>}[Percent Earned for Metric]) 
				          	  ),
				            RangeAvg(
				              	Avg(Aggr(Sum({<YearEnd={$(=$(v_Last_YearEnd))}>}[Points Earned for Metric]) / Sum({<YearEnd={$(=$(v_Last_YearEnd))}>}[Points Possible for Metric]), [%SchoolReportYearKey])),
				              	Avg(Aggr(Sum({<YearEnd={$(=$(v_LastLast_YearEnd))}>}[Points Earned for Metric]) / Sum({<YearEnd={$(=$(v_LastLast_YearEnd))}>}[Points Possible for Metric]), [%SchoolReportYearKey])),
				              	Avg(Aggr(Sum({<YearEnd={$(=$(v_LastLastLast_YearEnd))}>}[Points Earned for Metric]) / Sum({<YearEnd={$(=$(v_LastLastLast_YearEnd))}>}[Points Possible for Metric]), [%SchoolReportYearKey]))
				            )
				        )
				    )
				)
				, '#0.#%');


			let vLab_Avg_PercScore_OverallToDomainToMetric_3Year_Previous = $(vTitle_Avg_PercScore_OverallToDomainToMetric_3Year_Current)  & ' (up to '& $(v_Last_Year) &')';
		
			// The change in the average percent of possible points earned from the previous 3-year period to the most recent 3-year period. If multiple metrics are selected, this is equal to overall score. If a selection on Domain is made and there are no selections on metric, this is equal to the score for the domain. If a single metric is selected, this is equal to the metric score.
			let vMM_Avg_PercScore_OverallToDomainToMetric_3Year_YOY = Num(
					Round($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Current) - $(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Previous), 0.001)
				, '#0.#%');


			let vLab_Avg_PercScore_OverallToDomainToMetric_3Year_YOY = 'YOY: ' & $(vTitle_Avg_PercScore_OverallToDomainToMetric_3Year_Current);
		
	//// KPI  (top-right-middle): % of schools classified as model or reinforce
		/// Title
			// '% of "Model" and "Reinforce" School Reports'

		/// SubTitle
			let vSubTitle_Ratio_Reports_ModelReinforce = $(vMM_Count_Reports_ModelReinforce_Current) & ' of ' & $(vMM_Count_Reports_Current) & ' Reports (' & $(v_Max_Year) & ')';
			
		/// Measure 1:
			// The % of school reports with overall scores that put them in either the "Model" and "Reinforce" tiers (scores >= 50).	
			let vMM_Ratio_Reports_ModelReinforce_Current = Num($(vMM_Count_Reports_ModelReinforce_Current) / $(vMM_Count_Reports_Current), '#0.#%');

			let vLab_Ratio_Reports_ModelReinforce_Current = '% of "Model" and "Reinforce" School Reports ('& $(v_Max_Year) &')';

		/// Measure 2:
			// The change from the previous to most recent year in the percent of school reports with overall scores that put them in either the "Model" and "Reinforce" tiers (scores >= 50).
			let vMM_Ratio_Reports_ModelReinforce_YOY = Num($(vMM_Ratio_Reports_ModelReinforce_Current) - $(vMM_Count_Reports_ModelReinforce_Previous) / $(vMM_Count_Reports_Previous), '#0.#%');

			let vLab_Ratio_Reports_ModelReinforce_YOY = 'YOY: % of "Model" and "Reinforce" School Reports';

	//// KPI  (top-right): % of students in schools classified as model or reinforce
		/// Title
			// % of Students in "Model" and "Reinforce" School Reports

		/// SubTitle
			let vSubTitle_Ratio_Students_ModelReinforce = $(vMM_Count_Students_ModelReinforce_Current) & ' of ' & $(vMM_Count_Students_Current) & ' Students (' & $(v_Max_Year) & ')';
			
		/// Measure 1:
			// The % of students in schools with overall scores that put them in either the "Model" and "Reinforce" tiers (scores >= 50).	
			let vMM_Ratio_Students_ModelReinforce_Current = Num($(vMM_Count_Students_ModelReinforce_Current) / $(vMM_Count_Students_Current), '#0.#%');

			let vLab_Ratio_Students_ModelReinforce_Current = '% of Students in "Model" and "Reinforce" School Reports ('& $(v_Max_Year) &')';

		/// Measure 1:
			// The change from the previous to most recent year in the percent of students in schools with overall scores that put them in either the "Model" and "Reinforce" tiers (scores >= 50).
			let vMM_Ratio_Students_ModelReinforce_YOY = Num($(vMM_Ratio_Students_ModelReinforce_Current) - $(vMM_Count_Students_ModelReinforce_Previous) / $(vMM_Count_Students_Previous), '#0.#%');

			let vLab_Ratio_Students_ModelReinforce_YOY = 'YOY: % of Students in "Model" and "Reinforce" School Reports';

	//// Combo Chart (bottom-left): Average by Domain, drill to metric
		/// Title
			let vTitle_Avg_PercScore_DomainToMetric = 
				If($(vExpr_MultipleDomainsPossible_AllMetricsPossible), 
					'Average Score, by each Domain',
					If($(vExpr_SingleDomainSelected),
						'Average Score, by each Metric in ' & Only(GetFieldSelections([Domain Name])),
						'Average Score, by each Metric'
				));

		/// SubTitle

		/// Measure 1
			// The percent of possible points earned for all available metrics in the most current year. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PercScore_DomainToMetric_Current = Num(
					IF($(vExpr_MultipleDomainsPossible_AllMetricsPossible),		        	
					  Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned in Domain])
					  ,
			          Avg(Aggr(Sum({<YearEnd={$(=$(v_Max_YearEnd))}>}[Points Earned for Metric]) / Sum({<YearEnd={$(=$(v_Max_YearEnd))}>}[Points Possible for Metric]), [%SchoolReportYearMetricKey]))
			        )
					+ 0.0001, '#0%');

			let vLab_Avg_PercScore_DomainToMetric_Current = If($(vExpr_SingleDomainSelected), 'Average Score for Metrics in ' & Only(GetFieldSelections([Domain Name])), 'Average Score for Domains') &
				' ('& $(v_Max_Year) &')';

		/// Measure 2
			// The percent of possible points earned for all available metrics in the previous year. Without selections this defaults to the domain level.  If a single domain is selected this will display individual metrics
			let vMM_Avg_PercScore_DomainToMetric_Previous = Num(
					IF($(vExpr_MultipleDomainsPossible_AllMetricsPossible),		     	
			          Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned in Domain]),
			          Avg(Aggr(Sum({<IsSum={0}, YearEnd={$(=$(v_Last_YearEnd))}>}[Points Earned]) / Sum({<IsSum={0}, YearEnd={$(=$(v_Last_YearEnd))}>}[Points Possible]), [%SchoolReportYearMetricKey]))
			        )
					+ 0.0001, '#0%');

			let vLab_Avg_PercScore_DomainToMetric_Previous = If($(vExpr_SingleDomainSelected), 'Average Score for Metrics in ' & Only(GetFieldSelections([Domain Name])), 'Average Score for Domains') &
				' ('& $(v_Last_Year) &')';

		/// Color
			let vCol_Avg_PercScore_DomainToMetric_Current = 
				IF($(vMM_Avg_PercScore_DomainToMetric_Current) < 0.25, rgb(192,80,77),
				IF($(vMM_Avg_PercScore_DomainToMetric_Current) < 0.5, rgb(247,150,70),
				IF($(vMM_Avg_PercScore_DomainToMetric_Current)  < 0.75, rgb(0,176,80),
				IF($(vMM_Avg_PercScore_DomainToMetric_Current) >= 0.75, rgb(0,112,192)))));

	//// Line Chart (bottom-left-middle): 3 Year Average by Domain, drill to metric
		/// Title
			let vTitle_Avg_PercScore_DomainToMetric_3Year_Current = 
				If($(vExpr_MultipleDomainsPossible_AllMetricsPossible), 
					'Average Score, Overall',
					If($(vExpr_SingleDomainSelected),
						'Average Score, ' & Only(GetFieldSelections([Domain Name])),
						If($(vExpr_SingleMetricSelected),
							'Average Score, ' & Only(GetFieldSelections([Metric Name])),
							'Average Score, Selected Metrics'
						)
				));

		/// SubTitle

		/// Measure 1
			// vMM_Avg_PercScore_OverallToDomainToMetric_3Year
			
		/// Color
			let vCol_Avg_PercScore_DomainToMetric_3Year_Current = 
				IF($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Current) < 0.25, rgb(192,80,77),
				IF($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Current) < 0.5, rgb(247,150,70),
				IF($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Current)  < 0.75, rgb(0,176,80),
				IF($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Current) >= 0.75, rgb(0,112,192)))));

	//// Combo Chart (bottom-right-middle): % of Schools in each Tier
		/// Title
			// '% of School Reports in each Tier'

		/// Subtitle

		/// Measure 1
			// vMM_Count_Reports_Current

		/// Measure 2
			// vMM_Count_Reports_Previous

		/// Color
			let vCol_Tier = 
				IF([Tier] = 'Intervene', rgb(192,80,77),
				IF([Tier] = 'Watch', rgb(247,150,70),
				IF([Tier] = 'Reinforce', rgb(0,176,80),
				IF([Tier] = 'Model', rgb(0,112,192)))));

	//// Combo Chart (bottom-right-middle): % of Schools in each Tier
		/// Title
			// '% of Students in Schools From each Tier'

		/// Subtitle

		/// Measure 1
			// vMM_Count_Students_Current

		/// Measure 2
			// vMM_Count_Students_Previous

		/// Color
			// vCol_OverallTier

///// YOY Scores (by Network, Domain, Metric)
	//// Combo Chart (center): Average Schore by Network, School Report

		/// Title
			let vTitle_Avg_PercScore_NetworkToDomainToMetric = 
				If(GetPossibleCount([Learning Network]) = 1, 
					IF ($(vExpr_MultipleDomainsPossible_AllMetricsPossible),
		                'Average Score for each Domain in ' & Only(GetFieldSelections([Learning Network])),
		                'Average Score for each ' & Only(GetFieldSelections([Domain Name])) & ' Metric in ' & Only(GetFieldSelections([Learning Network]))
		            ),
		            $(vTitle_Avg_PercScore_OverallToDomainToMetric)
				);

		/// SubTitle
			let vSubTitle_Avg_PercScore_NetworkToDomainToMetric = 'Colored by change from ' & $(v_Last_Year) & ' to ' & $(v_Max_Year);

		/// Measure 1
			// SPR Score for the current year. If a single network is selected, will display each domain score, separately. If a single network and a single domain score is selected, will display each metric score, separately. If a specific network is not selected, will display either the overall, domain, or metric score selected for each network, based upon domain and metric selections. 
			let vMM_Avg_PercScore_NetworkToDomainToMetric_Current = Num(
				IF (GetPossibleCount([Learning Network]) > 1 and $(vExpr_AllDomainsPossible),
					Avg({<YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned Overall]),
				    IF (GetPossibleCount([Learning Network]) = 1,
                    	IF ($(vExpr_MultipleDomainsPossible_AllMetricsPossible),
                        	Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned in Domain]),
                            Avg({<YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned for Metric])
                        ),
                        IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
                    		Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned in Domain]),
				    		IF ($(vExpr_SingleMetricSelected), 
				        		Avg({<YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned for Metric]),
				            	Avg(Aggr(Sum({<YearEnd={$(=$(v_Max_YearEnd))}>}[Points Earned for Metric]) / Sum({<YearEnd={$(=$(v_Max_YearEnd))}>}[Points Possible for Metric]), [%SchoolReportYearKey]))
                            )
				        )
				    )
				)
				+ 0.0001, '#0%');

			let vLab_Avg_PercScore_NetworkToDomainToMetric_Current = 
				IF(GetPossibleCount([Learning Network]) = 1,
					IF ($(vExpr_MultipleDomainsPossible_AllMetricsPossible),
	                    'Average Score by Domain',
	                    'Average Score by Metric in ' & Only(GetFieldSelections([Domain Name]))
	                ),
					$(vTitle_Avg_PercScore_OverallToDomainToMetric)
				) & ' (' & $(v_Max_Year) &')';


		// Measure 2
			// SPR Score for the previous year. If a single network is selected, will display each domain score, separately. If a single network and a single domain score is selected, will display each metric score, separately. If a specific network is not selected, will display either the overall, domain, or metric score selected for each network, based upon domain and metric selections. 
			let vMM_Avg_PercScore_NetworkToDomainToMetric_Previous = Num(
				IF (GetPossibleCount([Learning Network]) > 1 and $(vExpr_AllDomainsPossible),
					Avg({<YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned Overall]),
				    IF (GetPossibleCount([Learning Network]) = 1,
                    	IF ($(vExpr_MultipleDomainsPossible_AllMetricsPossible),
                        	Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned in Domain]),
                            Avg({<YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned for Metric])
                        ),
                        IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
                    		Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned in Domain]),
				    		IF ($(vExpr_SingleMetricSelected), 
				        		Avg({<YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned for Metric]),
				            	Avg(Aggr(Sum({<YearEnd={$(=$(v_Last_YearEnd))}>}[Points Earned for Metric]) / Sum({<YearEnd={$(=$(v_Last_YearEnd))}>}[Points Possible for Metric]), [%SchoolReportYearKey]))
                            )
				        )
				    )
				)
				+ 0.0001, '#0%');

			let vLab_Avg_PercScore_NetworkToDomainToMetric_Previous = 
				IF(GetPossibleCount([Learning Network]) = 1,
					IF ($(vExpr_MultipleDomainsPossible_AllMetricsPossible),
	                    'Average Score by Domain',
	                    'Average Score by Metric in ' & Only(GetFieldSelections([Domain Name]))
	                ),
					$(vTitle_Avg_PercScore_OverallToDomainToMetric)
				) & ' (' & $(v_Max_Year) &')';

			// Change in SPR Score from the previous to the current year. If a single network is selected, will display each domain score, separately. If a single network and a single domain score is selected, will display each metric score, separately. If a specific network is not selected, will display either the overall, domain, or metric score selected for each network, based upon domain and metric selections. 
			let vMM_Avg_PercScore_NetworkToDomainToMetric_YOY = Num(
				Round($(vMM_Avg_PercScore_NetworkToDomainToMetric_Current) - $(vMM_Avg_PercScore_NetworkToDomainToMetric_Previous), 0.01)
				, '#0%');

			let vLab_Avg_PercScore_NetworkToDomainToMetric_YOY = 'YOY: ' & $(vTitle_Avg_PercScore_NetworkToDomainToMetric);	

		/// Color
			// $(vMM_Avg_PercScore_NetworkToDomainToMetric_YOY);

///// YOY Scores (by School, Domain, Metric)
	//// Combo Chart (center): Average Schore by Network, School Report

		/// Title
			let vTitle_Avg_PercScore_SchoolToDomainToMetric = 
				If(GetPossibleCount([School Abbrev Name (Reporting Category)]) = 1, 
					IF ($(vExpr_MultipleDomainsPossible_AllMetricsPossible),
		                'Average Score for each Domain in ' & Only(GetFieldSelections([School Abbrev Name (Reporting Category)])),
		                'Average Score for each ' & Only(GetFieldSelections([Domain Name])) & ' Metric in ' & Only(GetFieldSelections([School Abbrev Name (Reporting Category)]))
		            ),
		            $(vTitle_Avg_PercScore_OverallToDomainToMetric)
				);

		/// SubTitle
			let vSubTitle_Avg_PercScore_SchoolToDomainToMetric = 'Colored by change from ' & $(v_Last_Year) & ' to ' & $(v_Max_Year);

		/// Measure 1
			// SPR Score for the current year. If a single school is selected, will display each domain score, separately. If a single school and a single domain score is selected, will display each metric score, separately. If a specific network is not selected, will display either the overall, domain, or metric score selected for each network, based upon domain and metric selections. 
			let vMM_Avg_PercScore_SchoolToDomainToMetric_Current = Num(
				IF (GetPossibleCount([School Abbrev Name (Reporting Category)]) > 1 and $(vExpr_AllDomainsPossible),
					Avg({<YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned Overall]),
				    IF (GetPossibleCount([School Abbrev Name (Reporting Category)]) = 1,
                    	IF ($(vExpr_MultipleDomainsPossible_AllMetricsPossible),
                        	Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned in Domain]),
                            Avg({<YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned for Metric])
                        ),
                        IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
                    		Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned in Domain]),
				    		IF ($(vExpr_SingleMetricSelected),
				        		Avg({<YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned for Metric]),
				            	Avg(Aggr(Sum({<YearEnd={$(=$(v_Max_YearEnd))}>}[Points Earned for Metric]) / Sum({<YearEnd={$(=$(v_Max_YearEnd))}>}[Points Possible for Metric]), [%SchoolReportYearKey]))
                            )
				        )
				    )
				)
				+ 0.0001, '#0%');

			let vLab_Avg_PercScore_SchoolToDomainToMetric_Current = 
				IF(GetPossibleCount([School Abbrev Name (Reporting Category)]) = 1,
					IF ($(vExpr_MultipleDomainsPossible_AllMetricsPossible),
	                    'Average Score by Domain',
	                    'Average Score by Metric in ' & Only(GetFieldSelections([Domain Name]))
	                ),
					$(vTitle_Avg_PercScore_OverallToDomainToMetric)
				) & ' (' & $(v_Max_Year) &')';


		// Measure 2
			// SPR Score for the previous year. If a single school is selected, will display each domain score, separately. If a single school and a single domain score is selected, will display each metric score, separately. If a specific network is not selected, will display either the overall, domain, or metric score selected for each network, based upon domain and metric selections. 
			let vMM_Avg_PercScore_SchoolToDomainToMetric_Previous = Num(
				IF (GetPossibleCount([School Abbrev Name (Reporting Category)]) > 1 and $(vExpr_AllDomainsPossible),
					Avg({<YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned Overall]),
				    IF (GetPossibleCount([School Abbrev Name (Reporting Category)]) = 1,
                    	IF ($(vExpr_MultipleDomainsPossible_AllMetricsPossible),
                        	Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned in Domain]),
                            Avg({<YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned for Metric])
                        ),
                        IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
                    		Avg({<[Metric ID] = {"Z_ACH_OVERALL", "Z_PROG_OVERALL", "Z_CLIM_OVERALL", "Z_CC_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned in Domain]),
				    		IF ($(vExpr_SingleMetricSelected),
				        		Avg({<YearEnd={$(=$(v_Last_YearEnd))}>}[Percent Earned for Metric]),
				            	Avg(Aggr(Sum({<YearEnd={$(=$(v_Last_YearEnd))}>}[Points Earned for Metric]) / Sum({<YearEnd={$(=$(v_Last_YearEnd))}>}[Points Possible for Metric]), [%SchoolReportYearKey]))
                            )
				        )
				    )
				)
				+ 0.0001, '#0%');

			let vLab_Avg_PercScore_SchoolToDomainToMetric_Previous = 
				IF(GetPossibleCount([School Abbrev Name (Reporting Category)]) = 1,
					IF ($(vExpr_MultipleDomainsPossible_AllMetricsPossible),
	                    'Average Score by Domain',
	                    'Average Score by Metric in ' & Only(GetFieldSelections([Domain Name]))
	                ),
					$(vTitle_Avg_PercScore_OverallToDomainToMetric)
				) & ' (' & $(v_Max_Year) &')';

			// Change in SPR Score from the previous to the current year. If a single school is selected, will display each domain score, separately. If a single school and a single domain score is selected, will display each metric score, separately. If a specific network is not selected, will display either the overall, domain, or metric score selected for each network, based upon domain and metric selections. 
			let vMM_Avg_PercScore_SchoolToDomainToMetric_YOY = Num(
				Round($(vMM_Avg_PercScore_SchoolToDomainToMetric_Current) - $(vMM_Avg_PercScore_SchoolToDomainToMetric_Previous), 0.01)
				, '#0%');

			let vLab_Avg_PercScore_SchoolToDomainToMetric_YOY = 'YOY: ' & $(vTitle_Avg_PercScore_SchoolToDomainToMetric);	

		/// Color
			// $(vMM_Avg_PercScore_SchoolToDomainToMetric_YOY);

///// Points Possible and Points Earned (Scoring Page)

	let vSheet_Points_Possible_and_Points_Earned = 'Points Possible and Points Earned for ' & $(v_SelectedOrFirst_ReportType) & ' Report'; 

	//// Since this page must default to a specific report type, create a variable to store this
	let v_SelectedOrFirst_ReportType = FirstSortedValue(distinct [SPR Report Type], [SPR Report Type]);

	//// KPI 1 - # of points possible
		/// Measure 1
			// Average Points Possible for the current year for the selected report type. If multiple metrics are selected, this is equal to overall score. If a selection on Domain is made and there are no selections on metric, this is equal to the score for the domain. If a single metric is selected, this is equal to the metric score.
			let vMM_Avg_PointsPossible_Report_OverallToDomainToMetric_Current = Num(
				IF ($(vExpr_AllDomainsPossible),
					Avg({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Possible Overall]),
				    IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
				    	Avg({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Possible in Domain]),
				        IF ($(vExpr_SingleMetricSelected),
				        	Avg({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Possible for Metric]),
				            Avg(Aggr(Sum({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Possible for Metric]), [%SchoolReportYearKey]))
				        )
				    )
				)
				, '#0.#');

			let vLab_Avg_PointsPossible_Report_OverallToDomainToMetric_Current = 
				IF($(vExpr_SingleDomainSelected_or_SingleMetricSelected),
			    		IF($(vExpr_SingleDomainSelected_AllMetricsPossible), 'Average Points Possible for ' & Only(GetFieldSelections([Domain Name])),
				        IF($(vExpr_MultipleDomainsPossible_AllMetricsPossible), 'Average Points Possible for Selected Domains',
				        IF($(vExpr_MultipleMetricsSelected), 'Average Points Possible for Selected Metrics',
		                IF($(vExpr_SingleMetricSelected), 'Average Points Possible in ' & Only(GetFieldSelections([Metric Name]))
			        )))),
					'Average Overall Points Possible')
		    		& ' (' & $(v_SelectedOrFirst_ReportType) & ', ' & $(v_Max_Year) &')';
		/// Measure 2

			let vMM_Max_PointsPossible_OverallToDomainToMetric_Current = Max({<YearEnd={$(=$(v_Max_YearEnd))}, [School Name]=, [Learning Network]=, [Peer Group]= >} Aggr(Sum({<YearEnd={$(=$(v_Max_YearEnd))}, [School Name]=, [Learning Network]=, [Peer Group]= >}[Points Possible for Metric]), [%SchoolReportYearKey]));

	//// KPI 2 - # of points earned
		// Average Points Earned for the current year for the selected report type. If multiple metrics are selected, this is equal to overall score. If a selection on Domain is made and there are no selections on metric, this is equal to the score for the domain. If a single metric is selected, this is equal to the metric score.
		let vMM_Avg_PointsEarned_Report_OverallToDomainToMetric_Current = Num(
			IF ($(vExpr_AllDomainsPossible),
				Avg({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Earned Overall]),
			    IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
			    	Avg({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Earned in Domain]),
			        IF ($(vExpr_SingleMetricSelected),
			        	Avg({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Earned for Metric]),
			            Avg(Aggr(Sum({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Earned for Metric]), [%SchoolReportYearKey]))
			        )
			    )
			)
			, '#0.#');

		let vLab_Avg_PointsEarned_Report_OverallToDomainToMetric_Current = 
			IF($(vExpr_SingleDomainSelected_or_SingleMetricSelected),
		    	IF($(vExpr_SingleDomainSelected_AllMetricsPossible), 'Average Points Earned for ' & Only(GetFieldSelections([Domain Name])),
			        IF($(vExpr_MultipleDomainsPossible_AllMetricsPossible), 'Average Points Earned for Selected Domains',
			        	IF($(vExpr_MultipleMetricsSelected), 'Average Points Earned for Selected Metrics',
	                	IF($(vExpr_SingleMetricSelected), 'Average Points Earned in ' & Only(GetFieldSelections([Metric Name]))
		        )))),
				'Average Overall Points Earned')
	  			& ' (' & $(v_SelectedOrFirst_ReportType) & ', ' & $(v_Max_Year) &')';

	//// KPI 3 - % of points earned
		// SPR Score for the current year for the selected report type. If multiple metrics are selected, this is equal to overall score. If a selection on Domain is made and there are no selections on metric, this is equal to the score for the domain. If a single metric is selected, this is equal to the metric score.
		let vMM_Avg_PercScore_Report_OverallToDomainToMetric_Current = Num(
			IF ($(vExpr_AllDomainsPossible),
				Avg({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned Overall]),
			    IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
			    	Avg({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned in Domain]),
			        IF ($(vExpr_SingleMetricSelected),
			        	Avg({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned for Metric]),
			            Avg(Aggr(Sum({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Earned for Metric]) / Sum({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Possible for Metric]), [%SchoolReportYearKey]))
			        )
			    )
			)
			, '#0%');

		let vLab_Avg_PercScore_Report_OverallToDomainToMetric_Current = $(vTitle_Avg_PercScore_OverallToDomainToMetric) & ' (' & $(v_SelectedOrFirst_ReportType) & ', ' & $(v_Max_Year) &')';


	//// KPI 4 - Current Tier
		// Aperage Tier for the current year (< 0.25 = 'Intervene', < 0.50 = 'Watch', < .75 = 'Reinforce', >= 'Model'). If multiple metrics are selected, this is equal to overall score. If a selection on Domain is made and there are no selections on metric, this is equal to the score for the domain. If a single metric is selected, this is equal to the metric score.
		let vMM_Avg_Tier_Report_OverallToDomainToMetric_Current = If($(vMM_Avg_PercScore_Report_OverallToDomainToMetric_Current) < 0.25, 'Intervene',
			IF ($(vMM_Avg_PercScore_Report_OverallToDomainToMetric_Current) < 0.5, 'Watch',
			IF ($(vMM_Avg_PercScore_Report_OverallToDomainToMetric_Current) < 0.75, 'Reinforce',
			IF ($(vMM_Avg_PercScore_Report_OverallToDomainToMetric_Current) >= 0.75, 'Model'))));

		let vLab_Avg_Tier_Report_OverallToDomainToMetric_Current = IF($(vExpr_SingleDomainSelected_or_SingleMetricSelected),
		    	IF($(vExpr_SingleDomainSelected_AllMetricsPossible), 'Average Tier for ' & Only(GetFieldSelections([Domain Name])),
		        	IF($(vExpr_MultipleDomainsPossible_AllMetricsPossible), 'Average Tier for Selected Domains',
		        		IF($(vExpr_MultipleMetricsSelected), 'Average Tier for Selected Metrics',
                		IF($(vExpr_SingleMetricSelected), 'Average Tier in ' & Only(GetFieldSelections([Metric Name]))
		        )))),
				'Average Overall Tier')
	    		& ' (' & $(v_SelectedOrFirst_ReportType) & ', ' & $(v_Max_Year) &')';

	//// TreeMap (Bottom) - Displays size by number of points, color by tier
		/// Title
			let vTitle_Scoring_Report_DomainToMetric =  
				If($(vExpr_SingleDomainSelected), 
					'The Distribution of Points across Metrics in' & Only(GetFieldSelections([Domain Name])), 
					'The Distribution of Points across Domains'
				) & ' for ' & $(v_SelectedOrFirst_ReportType) & ' Report Type';

		/// Subtitle:
			let vSubTitle_Scoring_Report_DomainToMetric = 'Size indicates # of possible points in each ' & 
				If($(vExpr_SingleDomainSelected), 
					'Metric in ' & Only(GetFieldSelections([Domain Name])), 
					'Domain'
				) & '. Color indicates ' & 
				IF(GetSelectedCount([School Name])=1, ' Tiers achieved by ' & Only(GetFieldSelections([School Name])),
					IF(GetSelectedCount([School Name])>1, ' average Tiers achieved by Selected Schools',
						IF(GetSelectedCount([Learning Network])=1, ' average Tier achieved in ' & Only(GetFieldSelections([Learning Network])),
						IF(GetSelectedCount([Learning Network])>1, ' average Tier achieved in Selected Learning Networks',
						'average Tier achieved across all schools'))));	

		/// Measure (for size)
			// Displays the maximum number of points per domain. If a single domain is selected will show the maximum # of points per metric.
			let vMM_MaxScore_Report_DomainToMetric_Current = Num(
					If(GetPossibleCount([Domain Name]) = 1, 
						Max({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, IsSum={0}, YearEnd={$(=$(v_Max_YearEnd))}, [Metric Name]=, [Metric ID]=>}[Points Possible]),  
						Max({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, YearEnd={$(=$(v_Max_YearEnd))},[Domain Name]=, [Metric Name]=, [Metric ID]=>}[Points Possible in Domain])
					)
				, '#,##0.#');

			let vLab_MaxScore_Report_DomainToMetric_Current = 
				If(GetPossibleCount([Domain Name]) = 1, 
					'Max Points for Metric', 
					'Max Points in Domain'
				) & ' for ' & $(v_SelectedOrFirst_ReportType) & ' Report Type';
		

		/// Color
			// The percent of possible points earned for all available metrics in the most current year. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PercScore_Report_DomainToMetric_Current = Num(
					If(GetPossibleCount([Domain Name]) = 1, 
						Avg({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, IsSum={0}, YearEnd={$(=$(v_Max_YearEnd))}>}[Percent Earned]),  
						Avg({<[SPR Report Type] = {"$(=$(v_SelectedOrFirst_ReportType))"}, YearEnd={$(=$(v_Max_YearEnd))},[Metric Name]=, [Metric ID]=>}[Percent Earned in Domain])
					)
					+ 0.0001, '#0%');

			let vLab_Avg_PercScore_Report_DomainToMetric_Current = If($(vExpr_SingleDomainSelected), 'Average Score for Metrics in ' & Only(GetFieldSelections([Domain Name])), 'Average Score for Domains') &
				' (' & $(v_SelectedOrFirst_ReportType) & ', ' & $(v_Max_Year) &')';


			let vCol_Avg_PercScore_Report_DomainToMetric_Current = 
				IF($(vMM_Avg_PercScore_Report_DomainToMetric_Current) < 0.25, rgb(192,80,77),
				IF($(vMM_Avg_PercScore_Report_DomainToMetric_Current) < 0.5, rgb(247,150,70),
				IF($(vMM_Avg_PercScore_Report_DomainToMetric_Current) < 0.75, rgb(0,176,80),
				IF($(vMM_Avg_PercScore_Report_DomainToMetric_Current) >= 0.75, rgb(0,112,192)))));

///// Change from 2015-2016 to 2016-2017 (Sankey Page)

	//// Sheet Name
		let vSheet_Change_from_Previous_to_Current = 'Change from ' & $(v_Last_Year) & ' to ' & $(v_Max_Year);

	//// KPI  (top-left): # of school reports
		/// Title			
			

		/// Measure 1:
			// vMM_Count_Reports_Current	

	/// KPI 2: 

		/// Measure 1:
			// The # of schools that increased their SPR score.
			let vMM_Count_Reports_Increase_Current =  Num(
				IF ($(vExpr_AllDomainsPossible), 
					Sum(Aggr(If(Only(distinct {<[Metric ID] = {"Z_OVERALL_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]) - Only(distinct {<[Metric ID] = {"Z_OVERALL_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]) > 0, 1, 0), [%SchoolReportKey])),
					IF ($(vExpr_SingleDomainSelected_AllMetricsPossible), 
						If(Only(GetFieldSelections([Domain Name])) = 'Achievement', 
				       		Sum(Aggr(If(Only(distinct {<[Metric ID] = {"Z_ACH_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]) - Only(distinct {<[Metric ID] = {"Z_ACH_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]) > 0, 1, 0), [%SchoolReportKey])),
				        	If(Only(GetFieldSelections([Domain Name])) = 'Progress', 
				        		Sum(Aggr(If(Only(distinct {<[Metric ID] = {"Z_PROG_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]) - Only(distinct {<[Metric ID] = {"Z_PROG_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]) > 0, 1, 0), [%SchoolReportKey])),
					     	    If(Only(GetFieldSelections([Domain Name])) = 'Climate', 
				    		    	Sum(Aggr(If(Only(distinct {<[Metric ID] = {"Z_CLIM_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]) - Only(distinct {<[Metric ID] = {"Z_CLIM_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]) > 0, 1, 0), [%SchoolReportKey])),
				       				If(Only(GetFieldSelections([Domain Name])) = 'College & Career', 
				        				Sum(Aggr(If(Only(distinct {<[Metric ID] = {"Z_CC_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]) - Only(distinct {<[Metric ID] = {"Z_CC_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]) > 0, 1, 0), [%SchoolReportKey]))       
									)
								)
					        )
				       	),
						IF ($(vExpr_SingleMetricSelected), 
							Sum(Aggr(If(Only(distinct {<YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]) - Only(distinct {<YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]) > 0, 1, 0), [%SchoolReportKey]))
						)
					)
				),
				'##0');

			let vLab_Count_Reports_Increase_Current = '# of Schools that Increased their SPR Score';

		/// Measure 2:
			// The % of schools that increased their SPR score.
			let vMM_Ratio_Reports_Increase_Current =  Num(
				$(vMM_Count_Reports_Increase_Current) / $(vMM_Count_Reports_Current)				
				, '#0.#%');

			let vLab_Ratio_Reports_Increase_Current = '% of Schools that Increased their SPR Score';
	
	/// KPI 3: 

		/// Measure 1:
			// The # of schools that increased their SPR Tier level (such as Watch to Reinforce or Model).
			let vMM_Count_Reports_IncreaseTier_Current =  Num(			     
				IF ($(vExpr_AllDomainsPossible), 
					Sum(Aggr(If(Div(100 * Only( distinct {<[Metric ID] = {"Z_OVERALL_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]), 25) - Div(100 * Only( distinct {<[Metric ID] = {"Z_OVERALL_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]), 25) > 0, 1, 0), [%SchoolReportKey])),
					IF ($(vExpr_SingleDomainSelected_AllMetricsPossible), 
						If(Only( GetFieldSelections([Domain Name])) = 'Achievement', 
				        	Sum(Aggr(If(Div(100 * Only( distinct {<[Metric ID] = {"Z_ACH_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]), 25) - Div(100 * Only( distinct {<[Metric ID] = {"Z_ACH_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]), 25) > 0, 1, 0), [%SchoolReportKey])),
					        If(Only( GetFieldSelections([Domain Name])) = 'Progress', 
					        	Sum(Aggr(If(Div(100 * Only( distinct {<[Metric ID] = {"Z_PROG_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]), 25) - Div(100 * Only( distinct {<[Metric ID] = {"Z_PROG_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]), 25) > 0, 1, 0), [%SchoolReportKey])),
						        If(Only( GetFieldSelections([Domain Name])) = 'Climate', 
						        	Sum(Aggr(If(Div(100 * Only( distinct {<[Metric ID] = {"Z_CLIM_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]), 25) - Div(100 * Only( distinct {<[Metric ID] = {"Z_CLIM_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]), 25) > 0, 1, 0), [%SchoolReportKey])),
					   			    If(Only( GetFieldSelections([Domain Name])) = 'College & Career', 
					        			Sum(Aggr(If(Div(100 * Only( distinct {<[Metric ID] = {"Z_CC_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]), 25) - Div(100 * Only( distinct {<[Metric ID] = {"Z_CC_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]), 25) > 0, 1, 0), [%SchoolReportKey]))       
									)									
						        )
					        )
					    ),    
						IF ($(vExpr_SingleMetricSelected), 
							Sum(Aggr(If(Div(100 * Only( distinct {<YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]), 25) - Div(100 * Only( distinct {<YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]), 25) > 0, 1, 0), [%SchoolReportKey]))
						)
					)
				),
				'##0');

			let vLab_Count_Reports_IncreaseTier_Current = '# of Schools that Increased their SPR Tier';

		/// Measure 2:
			// The % of schools that increased their SPR Tier level (such as Watch to Reinforce or Model).
			let vMM_Ratio_Reports_IncreaseTier_Current =  Num(
				$(vMM_Count_Reports_IncreaseTier_Current) / $(vMM_Count_Reports_Current)				
				, '#0.#%');

			let vLab_Ratio_Reports_IncreaseTier_Current = '% of Schools that Increased their SPR Tier';

	/// KPI 4: 

		/// Measure 1:
			// The # of schools that moved from Intervene or Watch to Reinforce or Model.
			let vMM_Count_Reports_MovedToUpperTier_Current =  Num(
				IF ($(vExpr_AllDomainsPossible), 
					Sum(Aggr(If(Div(100 * Only( distinct {<[Metric ID] = {"Z_OVERALL_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]), 25) > 1 and Div(100 * Only( distinct {<[Metric ID] = {"Z_OVERALL_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]), 25) <= 1, 1, 0), [%SchoolReportKey])),
					IF ($(vExpr_SingleDomainSelected_AllMetricsPossible), 
						If(Only( GetFieldSelections([Domain Name])) = 'Achievement', 
				        	Sum(Aggr(If(Div(100 * Only( distinct {<[Metric ID] = {"Z_ACH_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]), 25) > 1 and Div(100 * Only( distinct {<[Metric ID] = {"Z_ACH_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]), 25) <= 1, 1, 0), [%SchoolReportKey])),
					        If(Only( GetFieldSelections([Domain Name])) = 'Progress', 
					        	Sum(Aggr(If(Div(100 * Only( distinct {<[Metric ID] = {"Z_PROG_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]), 25) > 1 and Div(100 * Only( distinct {<[Metric ID] = {"Z_PROG_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]), 25) <= 1, 1, 0), [%SchoolReportKey])),
						        If(Only( GetFieldSelections([Domain Name])) = 'Climate', 
						        	Sum(Aggr(If(Div(100 * Only( distinct {<[Metric ID] = {"Z_CLIM_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]), 25) > 1 and Div(100 * Only( distinct {<[Metric ID] = {"Z_CLIM_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]), 25) <= 1, 1, 0), [%SchoolReportKey])),
					   			    If(Only( GetFieldSelections([Domain Name])) = 'College & Career', 
					        			Sum(Aggr(If(Div(100 * Only( distinct {<[Metric ID] = {"Z_CC_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]), 25) > 1 and Div(100 * Only( distinct {<[Metric ID] = {"Z_CC_OVERALL"}, YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]), 25) <= 1, 1, 0), [%SchoolReportKey]))       
									)
								)
							)
					    ),
						IF ($(vExpr_SingleMetricSelected), 
							Sum(Aggr(If(Div(100 * Only( distinct {<YearEnd={$(=$(v_Max_YearEnd))}>} [Percent Earned]), 25) > 1 and Div(100 * Only( distinct {<YearEnd={$(=$(v_Last_YearEnd))}>} [Percent Earned]), 25) <= 1, 1, 0), [%SchoolReportKey]))
						)
					)
				),
				'##0');

			let vLab_Count_Reports_MovedToUpperTier_Current = '# of Schools that Moved to Highest 2 Tiers from Lowest 2';
	
		/// Measure 2:
			// The % of schools that moved from Intervene or Watch to Reinforce or Model.
			let vMM_Ratio_Reports_MovedToUpperTier_Current =  Num(
				$(vMM_Count_Reports_MovedToUpperTier_Current) / $(vMM_Count_Reports_Current)				
				, '#0.#%');

			let vLab_Ratio_Reports_MovedToUpperTier_Current = '% of Schools that Moved to Highest 2 Tiers from Lowest 2';

	//// Sankey (bottom-left)

		/// Variables for selecting the appropriate year
			let v_Sankey_Current = 
				If($(v_Max_YearEnd) = 2017, 'Tier (2016-2017)',
    			If($(v_Max_YearEnd) = 2016, 'Tier (2015-2016)',
    			If($(v_Max_YearEnd) = 2015, 'Tier (2014-2015)',
    			If($(v_Max_YearEnd) = 2014, 'Tier (2013-2014)',
    			If($(v_Max_YearEnd) = 2013, 'Tier (2012-2013)'
    			)))));

    		let v_Sankey_Previous = 
    			If($(v_Last_YearEnd) = 2016, 'Tier (2015-2016)',
    			If($(v_Last_YearEnd) = 2015, 'Tier (2014-2015)',
    			If($(v_Last_YearEnd) = 2014, 'Tier (2013-2014)',
    			If($(v_Last_YearEnd) = 2013, 'Tier (2012-2013)'
    			))));

			let v_Sankey_Previous2 = 
				If($(v_LastLast_YearEnd) = 2015, 'Tier (2014-2015)',
    			If($(v_LastLast_YearEnd) = 2014, 'Tier (2013-2014)',
    			If($(v_LastLast_YearEnd) = 2013, 'Tier (2012-2013)'
    			)));    		

		/// Measure (for size)
			let vMM_Count_Tier_OverallToDomainToMetric = Num(
				IF ($(vExpr_AllDomainsPossible), 
					Count(distinct {<[Points Possible] = {">0"}, [Metric ID] = {"Z_OVERALL_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [%SchoolReportMetricKey]),
					IF ($(vExpr_SingleDomainSelected_AllMetricsPossible), 
						If(Only(GetFieldSelections([Domain Name])) = 'Achievement', 
				        	Count(distinct {<[Points Possible] = {">0"}, [Metric ID] = {"Z_ACH_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [%SchoolReportMetricKey]),
					        If(Only(GetFieldSelections([Domain Name])) = 'Progress', 
					        	Count(distinct {<[Points Possible] = {">0"}, [Metric ID] = {"Z_PROG_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [%SchoolReportMetricKey]),
						        If(Only(GetFieldSelections([Domain Name])) = 'Climate', 
						        	Count(distinct {<[Points Possible] = {">0"}, [Metric ID] = {"Z_CLIM_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [%SchoolReportMetricKey]),
					   			    If(Only(GetFieldSelections([Domain Name])) = 'College & Career', 
					        			Count(distinct {<[Points Possible] = {">0"}, [Metric ID] = {"Z_CC_OVERALL"}, YearEnd={$(=$(v_Max_YearEnd))}>} [%SchoolReportMetricKey])            
									)
						        )
					        )
						),
						IF ($(vExpr_SingleMetricSelected), 
							Count(distinct {<[Points Possible] = {">0"}, YearEnd={$(=$(v_Max_YearEnd))}>} [%SchoolReportMetricKey])
						)
					)
				),
				'##0');

		/// Color Nodes (2016-2017)
			let vCol_OverallTier_Current =  
				IF([Tier ($(=$(v_Max_Year)))] = 'Intervene', 'rgb(192,80,77)',
				IF([Tier ($(=$(v_Max_Year)))] = 'Watch', 'rgb(247,150,70)',
				IF([Tier ($(=$(v_Max_Year)))] = 'Reinforce', 'rgb(0,176,80)',
				IF([Tier ($(=$(v_Max_Year)))] = 'Model', 'rgb(0,112,192)'))));
			

		/// Color Nodes (2015-2016)
			let vCol_OverallTier_Previous =  
				IF([Tier ($(=$(v_Last_Year)))] = 'Intervene', 'rgb(192,80,77)',
				IF([Tier ($(=$(v_Last_Year)))] = 'Watch', 'rgb(247,150,70)',
				IF([Tier ($(=$(v_Last_Year)))] = 'Reinforce', 'rgb(0,176,80)',
				IF([Tier ($(=$(v_Last_Year)))] = 'Model', 'rgb(0,112,192)'))));

		/// Color Nodes (2014-2015)
			let vCol_OverallTier_Previous2 =  
				IF([Tier ($(=$(v_LastLast_Year)))] = 'Intervene', 'rgb(192,80,77)',
				IF([Tier ($(=$(v_LastLast_Year)))] = 'Watch', 'rgb(247,150,70)',
				IF([Tier ($(=$(v_LastLast_Year)))] = 'Reinforce', 'rgb(0,176,80)',
				IF([Tier ($(=$(v_LastLast_Year)))] = 'Model', 'rgb(0,112,192)'))));


		/// Color Flow (2016-2017)
			let vCol_TierYOY_Previous = $(vCol_OverallTier_Current);
			let vCol_TierYOY_Previous2 = $(vCol_OverallTier_Previous);

		/// Sort (2016-2017)
			let vSort_OverallTier_Current = 
				IF([Tier ($(=$(v_Max_Year)))] = 'Intervene', 1,
				IF([Tier ($(=$(v_Max_Year)))] = 'Watch', 2,
				IF([Tier ($(=$(v_Max_Year)))] = 'Reinforce', 3,
				IF([Tier ($(=$(v_Max_Year)))] = 'Model', 4))));

		/// Sort (2015-2016)
			let vSort_OverallTier_Previous = 
				IF([Tier ($(=$(v_Last_Year)))] = 'Intervene', 1,
				IF([Tier ($(=$(v_Last_Year)))] = 'Watch', 2,
				IF([Tier ($(=$(v_Last_Year)))] = 'Reinforce', 3,
				IF([Tier ($(=$(v_Last_Year)))] = 'Model', 4))));

		/// Sort (2014-2015)
			let vSort_OverallTier_Previous2 = 
				IF([Tier ($(=$(v_LastLast_Year)))] = 'Intervene', 1,
				IF([Tier ($(=$(v_LastLast_Year)))] = 'Watch', 2,
				IF([Tier ($(=$(v_LastLast_Year)))] = 'Reinforce', 3,
				IF([Tier ($(=$(v_LastLast_Year)))] = 'Model', 4))));

	//// Table

		/// Measure 1 - Score Previous
			// vMM_Avg_PercScore_OverallToDomainToMetric_Previous

			// background coloring
			let vCol_Avg_PercScore_OverallToDomainToMetric_Previous = 
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_Previous) < 0.25, 'rgb(192,80,77)',
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_Previous) < 0.5, 'rgb(247,150,70)',
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_Previous) < 0.75, 'rgb(0,176,80)',
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_Previous) >= 0.75, 'rgb(0,112,192)'))));
		
		/// Measure 2 - Score Current
			//  vMM_Avg_PercScore_OverallToDomainToMetric_Current
			
			// background coloring
			let vCol_Avg_PercScore_OverallToDomainToMetric_Current = 
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_Current) < 0.25, 'rgb(192,80,77)',
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_Current) < 0.5, 'rgb(247,150,70)',
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_Current) < 0.75, 'rgb(0,176,80)',
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_Current) >= 0.75, 'rgb(0,112,192)'))));

		/// Measure 3 - Score Change 
			// vMM_Avg_PercScore_OverallToDomainToMetric_YOY 

			// background coloring
			let vCol_Avg_PercScore_OverallToDomainToMetric_YOY = 
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_YOY) < -0.2, '#AE1C3E',
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_YOY) < -0.1, '#ED875E',
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_YOY) < 0, '#F2D2AE',
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_YOY) < 0.1, '#D1EBFB',
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_YOY) < 0.2, '#5EA4D9',
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_YOY) >= 0.2, '#3C52A1'
				))))));

		
///// Map Sheet - User can select which metric to view based upon button selected
	let vSelectedMeasure = PercScore_Current;

	//// Button - Current Score
		let vButLab_Metric_Score_Current = 
			IF(vSelectedMeasure = 'PercScore_Current',
				chr(9658) & ' Current Score ' & chr(9668),
		    	'Current Score'
		    );

	//// Button - Previous Score
		let vButLab_Metric_Score_Previous = 
			IF(vSelectedMeasure = 'PercScore_Previous',
				chr(9658) & ' Previous Score ' & chr(9668),
		    	'Previous Score'
		    );

	//// Button - Current Score
		let vButLab_Metric_Score_YOY = 
			IF(vSelectedMeasure = 'PercScore_YOY',
				chr(9658) & ' YOY Score ' & chr(9668),
		    	'YOY Score'
		    );

	//// Button - Current Score
		let vButLab_Metric_Score_3Year_Current = 
			IF(vSelectedMeasure = 'PercScore_3Year_Current',
				chr(9658) & ' 3 Year Average Score ' & chr(9668),
		    	'3 Year Average Score'
		    );

	//// Map (Center-Left)
		/// Measure (for size)
			let vMM_Measure_Selected = 
				IF(vSelectedMeasure = 'PercScore_Current', $(vMM_Avg_PercScore_OverallToDomainToMetric_Current) * 100 + 0.1,
				IF(vSelectedMeasure = 'PercScore_Previous', $(vMM_Avg_PercScore_OverallToDomainToMetric_Previous) * 100 + 0.1,
				IF(vSelectedMeasure = 'PercScore_YOY', $(vMM_Avg_PercScore_OverallToDomainToMetric_YOY) * 100 + 0.1,
				IF(vSelectedMeasure = 'PercScore_3Year_Current', $(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Current) * 100 + 0.1
					))));
				
			// this isn't actually working as a real master measure, perhaps map will allow in an update.
			let vLab_Measure_Selected = 
				IF(vSelectedMeasure = 'PercScore_Current', $(vLab_Avg_PercScore_OverallToDomainToMetric_Current),
				IF(vSelectedMeasure = 'PercScore_Previous', $(vLab_Avg_PercScore_OverallToDomainToMetric_Previous),
				IF(vSelectedMeasure = 'PercScore_YOY', $(vLab_Avg_PercScore_OverallToDomainToMetric_YOY),
				IF(vSelectedMeasure = 'PercScore_3Year_Current', $(vLab_Avg_PercScore_OverallToDomainToMetric_3Year_Current)
					))));	

		/// Colors
			let vCol_Measure_Selected = 
				IF(vSelectedMeasure = 'PercScore_Current', 
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_Current) < 0.25, rgb(192,80,77),
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_Current) < 0.5, rgb(247,150,70),
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_Current) < 0.75, rgb(0,176,80),
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_Current) >= 0.75, rgb(0,112,192))))),
				IF(vSelectedMeasure = 'PercScore_3Year_Current', 
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Current) < 0.25, rgb(192,80,77),
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Current) < 0.5, rgb(247,150,70),
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Current)  < 0.75, rgb(0,176,80),
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Current) >= 0.75, rgb(0,112,192))))),
				IF(vSelectedMeasure = 'PercScore_Previous', 
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_Previous) < 0.25, rgb(192,80,77),
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_Previous) < 0.5, rgb(247,150,70),
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_Previous)  < 0.75, rgb(0,176,80),
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_Previous) >= 0.75, rgb(0,112,192))))),
				IF(vSelectedMeasure = 'PercScore_YOY', 
				    IF($(vMM_Avg_PercScore_OverallToDomainToMetric_YOY) <= -0.2, '#AE1C3E',
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_YOY) <= -0.1,'#ED875E',
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_YOY) < 0, '#F2D2AE',
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_YOY) < 0.1, '#D1EBFB',
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_YOY) < 0.2, '#5EA4D9',
					IF($(vMM_Avg_PercScore_OverallToDomainToMetric_YOY) >= 0.2, '#3C52A1')))))),
				))));

	//// Treemap Legend (bottom)
			let vColLegend_Measure_Selected = 
				If(vSelectedMeasure = 'PercScore_Current' or vSelectedMeasure = 'PercScore_Previous' or vSelectedMeasure = 'PercScore_3Year_Current',
					pick(
				    	match(
							valuelist('Intervene', 'Watch', 'Reinforce', 'Model','Decrease more than 20%','Decrease between 10% and 20%','Decrease less than 10%', 'Increase less than 10%', 'Increase between 10% and 20%', 'Increase more than 20%'),
				        	'Intervene', 'Watch', 'Reinforce', 'Model','Decrease more than 20%','Decrease between 10% and 20%','Decrease less than 10%', 'Increase less than 10%', 'Increase between 10% and 20%', 'Increase more than 20%'),
				        1.004,1.003,1.002,1.001,0.00000001,0.00000001,0.00000001,0.00000001,0.00000001,0.00000001)
				   , pick(
				    	match(
							valuelist('Intervene', 'Watch', 'Reinforce', 'Model','Decrease more than 20%','Decrease between 10% and 20%','Decrease less than 10%', 'Increase less than 10%', 'Increase between 10% and 20%', 'Increase more than 20%'),
				        	'Intervene', 'Watch', 'Reinforce', 'Model','Decrease more than 20%','Decrease between 10% and 20%','Decrease less than 10%', 'Increase less than 10%', 'Increase between 10% and 20%', 'Increase more than 20%'),
				        0.00000001,0.00000001,0.00000001,0.00000001,1.005,1.004,1.003,1.002,1.001,1.000));    

///// Achievement Domain Sheet
	//// Line Graph (top-left) - shows last 3 years of performance in the Achievement domain, drill to metrics
		/// Title
			let vTitle_Avg_PercScore_Achievement_3Year_Current = 'Average Achievement Score for Previous 3 Years';

		/// SubTitle
			let vSubTitle_Avg_PercScore_Achievement_3Year_Current = '';

		/// Measure 1
			// The average percent of possible points earned for all available "Achievement" metrics in the previous 3 years. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PercScore_Achievement_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Avg( {<[Domain Name] = {"Achievement"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Percent Earned in Domain]),
					Avg(Aggr(Sum({<[Domain Name] = {"Achievement"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Earned]) / Sum({<[Domain Name] = {"Achievement"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Possible]), [%SchoolReportYearKey]))
				), '#0%');

			let vLab_Avg_PercScore_Achievement_3Year_Current = 'Achievement: Average Score';	
			
		/// Color
			let vCol_Avg_PercScore_Achievement_3Year_Current = 
				IF($(vMM_Avg_PercScore_Achievement_3Year_Current) < 0.25, rgb(192,80,77),
				IF($(vMM_Avg_PercScore_Achievement_3Year_Current) < 0.5, rgb(247,150,70),
				IF($(vMM_Avg_PercScore_Achievement_3Year_Current)  < 0.75, rgb(0,176,80),
				IF($(vMM_Avg_PercScore_Achievement_3Year_Current) >= 0.75, rgb(0,112,192)))));

	
	
	//// Table (bottom-left)
		/// Measure 1: Achievement - # of reports
			// The number of "Achievement" reports in the most recent three years.
			let vMM_Count_Reports_Achievement_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Count(distinct {<[Points Possible in Domain] = {">0"}, [Domain Name] = {"Achievement"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearDomainKey),
					Count(distinct {<[Points Possible] = {">0"}, [Domain Name] = {"Achievement"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearKey)
				), '#,##0');
			let vLab_Count_Reports_Achievement_3Year_Current = 'Achievement: # of School Reports';
			
		/// Measure 2: Achievement - Average Points Possible
			// The average number of total possible points for all available "Achievement" metrics in the previous three years. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PointsPossible_Achievement_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Avg( {<[Domain Name] = {"Achievement"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Possible in Domain]),
					Avg(Aggr(Sum({<[Domain Name] = {"Achievement"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Possible]), %SchoolReportYearKey]))
				), '#0.#');
			let vLab_Avg_PointsPossible_Achievement_3Year_Current = 'Achievement: Average # of Points Possible';

		/// Measure 3: Achievement - Average Points Earned
			// The average number of points earned for all available "Achievement" metrics in the previous three years. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PointsEarned_Achievement_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Avg( {<[Domain Name] = {"Achievement"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Earned in Domain]),
					Avg(Aggr(Sum({<[Domain Name] = {"Achievement"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Earned]), %SchoolReportYearKey]))
				), '#0.#');
			let vLab_Avg_PointsEarned_Achievement_3Year_Current = 'Achievement: Average # of Points Earned';

		/// Measure 3: Achievement - Average Score %
			// vMM_Avg_PercScore_Achievement_3Year_Current 
			

		/// Measure 4: Achievement - Average Tier
			// The average tier for the "Achievement" achievement domain for the previous 3 years (< 0.25 = 'Intervene', < 0.50 = 'Watch', < .75 = 'Reinforce', >= 'Model'). Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_Tier_Achievement_3Year_Current = 
				If($(vMM_Avg_PercScore_Achievement_3Year_Current) < 0.25, 'Intervene',
				If($(vMM_Avg_PercScore_Achievement_3Year_Current) < 0.5, 'Watch',
				If($(vMM_Avg_PercScore_Achievement_3Year_Current) < 0.75, 'Reinforce',	
				If($(vMM_Avg_PercScore_Achievement_3Year_Current) >= 0.75, 'Model')))	
				);
			let vLab_Avg_Tier_Achievement_3Year_Current = 'Achievement: Average Tier';


		/// Measure 5: Achievement - # of reports in "model" or "reinforce"
			// The number of reports at the "Model" and "Reinforce" tier withing the "Achievement" domain.
			let vMM_Count_Reports_ModelReinforce_Achievement_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Count(distinct {<[Tier in Domain] = {"Model", "Reinforce"}, [Domain Name] = {"Achievement"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearDomainKey),
					Count(distinct {<[Tier in Domain] = {"Model", "Reinforce"}, [Domain Name] = {"Achievement"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearKey)
				), '#,##0');
			let vLab_Count_Reports_ModelReinforce_Achievement_3Year_Current = 'Achievement: # of "Model" and "Reinforce" School Reports';
		
		
		/// Color
			let vCol_YearEnd = If(YearEnd = 2017, '#398635', If(YearEnd = 2016, '#737373', If(YearEnd = 2015, '#BDBDBD', '#F0F0F0')));


	//// Bar Chart (right)
		/// Title
			let vTitle_Avg_PercScore_Achievement_Current = 'Average Achievement Score';

		/// SubTitle
			let vSubTitle_Avg_PercScore_Achievement_Current = '';	

		/// Measure 1
			// The percent of possible points earned for all available "Achievement" metrics in the most current year. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PercScore_AchievementToMetric_Current = Num(
				IF($(vExpr_MultipleMetricsSelected),
		        	Avg(Aggr(Sum({<IsSum={0}, [Domain Name]={"Achievement"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Earned]) / Sum({<IsSum={0}, [Domain Name]={"Achievement"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Possible]), [%SchoolReportYearKey]))
		              ,
		            Avg({<YearEnd={$(=$(v_Max_YearEnd))}, [Domain Name]={"Achievement"}>}[Percent Earned in Domain])
		        )					
				, '#0.#%');
			
			let vLab_Avg_PercScore_AchievementToMetric_Current = 
				IF($(vExpr_MultipleMetricsSelected),
		        	'Average Score in Achievement Domain ('& $(v_Max_Year) &')'
		              ,
		            'Average Score in Achievement Domain ('& $(v_Max_Year) &')'
		        );

		/// Color: vMM_Avg_PercScore_AchievementToMetric_Current 
			let vCol_Avg_PercScore_AchievementToMetric_Current = 
				IF($(vMM_Avg_PercScore_AchievementToMetric_Current) < 0.25, rgb(192,80,77),
				IF($(vMM_Avg_PercScore_AchievementToMetric_Current) < 0.5, rgb(247,150,70),
				IF($(vMM_Avg_PercScore_AchievementToMetric_Current)  < 0.75, rgb(0,176,80),
				IF($(vMM_Avg_PercScore_AchievementToMetric_Current) >= 0.75, rgb(0,112,192)))));

///// Progress Domain Sheet
	//// Line Graph (top-left) - shows last 3 years of performance in the Progress domain, drill to metrics
		/// Title
			let vTitle_Avg_PercScore_Progress_3Year_Current = 'Average Progress Score for Previous 3 Years';

		/// SubTitle
			let vSubTitle_Avg_PercScore_Progress_3Year_Current = '';

		/// Measure 1
			// The average percent of possible points earned for all available "Progress" metrics in the previous 3 years. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PercScore_Progress_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Avg( {<[Domain Name] = {"Progress"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Percent Earned in Domain]),
					Avg(Aggr(Sum({<[Domain Name] = {"Progress"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Earned]) / Sum({<[Domain Name] = {"Progress"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Possible]), [%SchoolReportYearKey]))
				), '#0%');

			let vLab_Avg_PercScore_Progress_3Year_Current = 'Progress: Average Score';	
			
		/// Color
			let vCol_Avg_PercScore_Progress_3Year_Current = 
				IF($(vMM_Avg_PercScore_Progress_3Year_Current) < 0.25, rgb(192,80,77),
				IF($(vMM_Avg_PercScore_Progress_3Year_Current) < 0.5, rgb(247,150,70),
				IF($(vMM_Avg_PercScore_Progress_3Year_Current)  < 0.75, rgb(0,176,80),
				IF($(vMM_Avg_PercScore_Progress_3Year_Current) >= 0.75, rgb(0,112,192)))));

	
	
	//// Table (bottom-left)
		/// Measure 1: Progress - # of reports
			// The number of "Progress" reports in the most recent three years.
			let vMM_Count_Reports_Progress_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Count(distinct {<[Points Possible in Domain] = {">0"}, [Domain Name] = {"Progress"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearDomainKey),
					Count(distinct {<[Points Possible] = {">0"}, [Domain Name] = {"Progress"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearKey)
				), '#,##0');
			let vLab_Count_Reports_Progress_3Year_Current = 'Progress: # of School Reports';
			
		/// Measure 2: Progress - Average Points Possible
			// The average number of total possible points for all available "Progress" metrics in the previous three years. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PointsPossible_Progress_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Avg( {<[Domain Name] = {"Progress"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Possible in Domain]),
					Avg(Aggr(Sum({<[Domain Name] = {"Progress"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Possible]), %SchoolReportYearKey]))
				), '#0.#');
			let vLab_Avg_PointsPossible_Progress_3Year_Current = 'Progress: Average # of Points Possible';

		/// Measure 3: Progress - Average Points Earned
			// The average number of points earned for all available "Progress" metrics in the previous three years. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PointsEarned_Progress_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Avg( {<[Domain Name] = {"Progress"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Earned in Domain]),
					Avg(Aggr(Sum({<[Domain Name] = {"Progress"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Earned]), %SchoolReportYearKey]))
				), '#0.#');
			let vLab_Avg_PointsEarned_Progress_3Year_Current = 'Progress: Average # of Points Earned';

		/// Measure 3: Progress - Average Score %
			// vMM_Avg_PercScore_Progress_3Year_Current 
			

		/// Measure 4: Progress - Average Tier
			// The average tier for the "Progress" achievement domain for the previous 3 years (< 0.25 = 'Intervene', < 0.50 = 'Watch', < .75 = 'Reinforce', >= 'Model'). Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_Tier_Progress_3Year_Current = 
				If($(vMM_Avg_PercScore_Progress_3Year_Current) < 0.25, 'Intervene',
					If($(vMM_Avg_PercScore_Progress_3Year_Current) < 0.5, 'Watch',
					If($(vMM_Avg_PercScore_Progress_3Year_Current) < 0.75, 'Reinforce',	
					If($(vMM_Avg_PercScore_Progress_3Year_Current) >= 0.75, 'Model')))	
				);
			let vLab_Avg_Tier_Progress_3Year_Current = 'Progress: Average Tier';


		/// Measure 5: Progress - # of reports in "model" or "reinforce"
			// The number of reports at the "Model" and "Reinforce" tier withing the "Progress" domain.
			let vMM_Count_Reports_ModelReinforce_Progress_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Count(distinct {<[Tier in Domain] = {"Model", "Reinforce"}, [Domain Name] = {"Progress"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearDomainKey),
					Count(distinct {<[Tier in Domain] = {"Model", "Reinforce"}, [Domain Name] = {"Progress"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearKey)
				), '#,##0');
			let vLab_Count_Reports_ModelReinforce_Progress_3Year_Current = 'Progress: # of "Model" and "Reinforce" School Reports';
		
		
		/// Color
			let vCol_YearEnd = If(YearEnd = 2017, '#398635', If(YearEnd = 2016, '#737373', If(YearEnd = 2015, '#BDBDBD', '#F0F0F0')));


	//// Bar Chart (right)
		/// Title
			let vTitle_Avg_PercScore_Progress_Current = 'Average Progress Score';

		/// SubTitle
			let vSubTitle_Avg_PercScore_Progress_Current = '';	

		/// Measure 1
			// The percent of possible points earned for all available "Progress" metrics in the most current year. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PercScore_ProgressToMetric_Current = Num(
				IF($(vExpr_MultipleMetricsSelected),
		        	Avg(Aggr(Sum({<IsSum={0}, [Domain Name]={"Progress"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Earned]) / Sum({<IsSum={0}, [Domain Name]={"Progress"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Possible]), [%SchoolReportYearKey]))
		              ,
		            Avg({<YearEnd={$(=$(v_Max_YearEnd))}, [Domain Name]={"Progress"}>}[Percent Earned in Domain])
		        )					
				, '#0.#%');
			
			let vLab_Avg_PercScore_ProgressToMetric_Current = 
				IF($(vExpr_MultipleMetricsSelected),
		        	'Average Score in Progress Domain ('& $(v_Max_Year) &')'
		              ,
		            'Average Score in Progress Domain ('& $(v_Max_Year) &')'
		        );

		/// Color:
			let vCol_Avg_PercScore_ProgressToMetric_Current = 
				IF($(vMM_Avg_PercScore_ProgressToMetric_Current) < 0.25, rgb(192,80,77),
					IF($(vMM_Avg_PercScore_ProgressToMetric_Current) < 0.5, rgb(247,150,70),
					IF($(vMM_Avg_PercScore_ProgressToMetric_Current)  < 0.75, rgb(0,176,80),
					IF($(vMM_Avg_PercScore_ProgressToMetric_Current) >= 0.75, rgb(0,112,192)))));

///// Climate Domain Sheet
	//// Line Graph (top-left) - shows last 3 years of performance in the Climate domain, drill to metrics
		/// Title
			let vTitle_Avg_PercScore_Climate_3Year_Current = 'Average Climate Score for Previous 3 Years';

		/// SubTitle
			let vSubTitle_Avg_PercScore_Climate_3Year_Current = '';

		/// Measure 1
			// The average percent of possible points earned for all available "Climate" metrics in the previous 3 years. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PercScore_Climate_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Avg( {<[Domain Name] = {"Climate"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Percent Earned in Domain]),
					Avg(Aggr(Sum({<[Domain Name] = {"Climate"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Earned]) / Sum({<[Domain Name] = {"Climate"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Possible]), [%SchoolReportYearKey]))
				), '#0%');

			let vLab_Avg_PercScore_Climate_3Year_Current = 'Climate: Average Score';	
			
		/// Color
			let vCol_Avg_PercScore_Climate_3Year_Current = 
				IF($(vMM_Avg_PercScore_Climate_3Year_Current) < 0.25, rgb(192,80,77),
				IF($(vMM_Avg_PercScore_Climate_3Year_Current) < 0.5, rgb(247,150,70),
				IF($(vMM_Avg_PercScore_Climate_3Year_Current)  < 0.75, rgb(0,176,80),
				IF($(vMM_Avg_PercScore_Climate_3Year_Current) >= 0.75, rgb(0,112,192)))));

	
	
	//// Table (bottom-left)
		/// Measure 1: Climate - # of reports
			// The number of "Climate" reports in the most recent three years.
			let vMM_Count_Reports_Climate_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Count(distinct {<[Points Possible in Domain] = {">0"}, [Domain Name] = {"Climate"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearDomainKey),
					Count(distinct {<[Points Possible] = {">0"}, [Domain Name] = {"Climate"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearKey)
				), '#,##0');
			let vLab_Count_Reports_Climate_3Year_Current = 'Climate: # of School Reports';
			
		/// Measure 2: Climate - Average Points Possible
			// The average number of total possible points for all available "Climate" metrics in the previous three years. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PointsPossible_Climate_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Avg( {<[Domain Name] = {"Climate"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Possible in Domain]),
					Avg(Aggr(Sum({<[Domain Name] = {"Climate"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Possible]), %SchoolReportYearKey]))
				), '#0.#');
			let vLab_Avg_PointsPossible_Climate_3Year_Current = 'Climate: Average # of Points Possible';

		/// Measure 3: Climate - Average Points Earned
			// The average number of points earned for all available "Climate" metrics in the previous three years. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PointsEarned_Climate_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Avg( {<[Domain Name] = {"Climate"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Earned in Domain]),
					Avg(Aggr(Sum({<[Domain Name] = {"Climate"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Earned]), %SchoolReportYearKey]))
				), '#0.#');
			let vLab_Avg_PointsEarned_Climate_3Year_Current = 'Climate: Average # of Points Earned';

		/// Measure 3: Climate - Average Score %
			// vMM_Avg_PercScore_Climate_3Year_Current 
			

		/// Measure 4: Climate - Average Tier
			// The average tier for the "Climate" achievement domain for the previous 3 years (< 0.25 = 'Intervene', < 0.50 = 'Watch', < .75 = 'Reinforce', >= 'Model'). Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_Tier_Climate_3Year_Current = 
				If($(vMM_Avg_PercScore_Climate_3Year_Current) < 0.25, 'Intervene',
					If($(vMM_Avg_PercScore_Climate_3Year_Current) < 0.5, 'Watch',
					If($(vMM_Avg_PercScore_Climate_3Year_Current) < 0.75, 'Reinforce',	
					If($(vMM_Avg_PercScore_Climate_3Year_Current) >= 0.75, 'Model')))	
				);
			let vLab_Avg_Tier_Climate_3Year_Current = 'Climate: Average Tier';


		/// Measure 5: Climate - # of reports in "model" or "reinforce"
			// The number of reports at the "Model" and "Reinforce" tier withing the "Climate" domain.
			let vMM_Count_Reports_ModelReinforce_Climate_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Count(distinct {<[Tier in Domain] = {"Model", "Reinforce"}, [Domain Name] = {"Climate"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearDomainKey),
					Count(distinct {<[Tier in Domain] = {"Model", "Reinforce"}, [Domain Name] = {"Climate"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearKey)
				), '#,##0');
			let vLab_Count_Reports_ModelReinforce_Climate_3Year_Current = 'Climate: # of "Model" and "Reinforce" School Reports';
		
		
		/// Color
			let vCol_YearEnd = If(YearEnd = 2017, '#398635', If(YearEnd = 2016, '#737373', If(YearEnd = 2015, '#BDBDBD', '#F0F0F0')));


	//// Bar Chart (right)
		/// Title
			let vTitle_Avg_PercScore_Climate_Current = 'Average Climate Score';

		/// SubTitle
			let vSubTitle_Avg_PercScore_Climate_Current = '';	

		/// Measure 1
			// The percent of possible points earned for all available "Climate" metrics in the most current year. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PercScore_ClimateToMetric_Current = Num(
				IF($(vExpr_MultipleMetricsSelected),
		        	Avg(Aggr(Sum({<IsSum={0}, [Domain Name]={"Climate"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Earned]) / Sum({<IsSum={0}, [Domain Name]={"Climate"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Possible]), [%SchoolReportYearKey]))
		              ,
		            Avg({<YearEnd={$(=$(v_Max_YearEnd))}, [Domain Name]={"Climate"}>}[Percent Earned in Domain])
		        )					
				, '#0.#%');
			
			let vLab_Avg_PercScore_ClimateToMetric_Current = 
				IF($(vExpr_MultipleMetricsSelected),
		        	'Average Score in Climate Domain ('& $(v_Max_Year) &')'
		              ,
		            'Average Score in Climate Domain ('& $(v_Max_Year) &')'
		        );

		/// Color:
			let vCol_Avg_PercScore_ClimateToMetric_Current = 
				IF($(vMM_Avg_PercScore_ClimateToMetric_Current) < 0.25, rgb(192,80,77),
					IF($(vMM_Avg_PercScore_ClimateToMetric_Current) < 0.5, rgb(247,150,70),
					IF($(vMM_Avg_PercScore_ClimateToMetric_Current)  < 0.75, rgb(0,176,80),
					IF($(vMM_Avg_PercScore_ClimateToMetric_Current) >= 0.75, rgb(0,112,192)))));

///// College & Career Domain Sheet
	//// Line Graph (top-left) - shows last 3 years of performance in the College & Career domain, drill to metrics
		/// Title
			let vTitle_Avg_PercScore_CollegeCareer_3Year_Current = 'Average College & Career Score for Previous 3 Years';

		/// SubTitle
			let vSubTitle_Avg_PercScore_CollegeCareer_3Year_Current = '';

		/// Measure 1
			// The average percent of possible points earned for all available "College & Career" metrics in the previous 3 years. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PercScore_CollegeCareer_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Avg( {<[Domain Name] = {"College & Career"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Percent Earned in Domain]),
					Avg(Aggr(Sum({<[Domain Name] = {"College & Career"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Earned]) / Sum({<[Domain Name] = {"College & Career"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Possible]), [%SchoolReportYearKey]))
				), '#0%');

			let vLab_Avg_PercScore_CollegeCareer_3Year_Current = 'College & Career: Average Score';	
			
		/// Color
			let vCol_Avg_PercScore_CollegeCareer_3Year_Current = 
				IF($(vMM_Avg_PercScore_CollegeCareer_3Year_Current) < 0.25, rgb(192,80,77),
					IF($(vMM_Avg_PercScore_CollegeCareer_3Year_Current) < 0.5, rgb(247,150,70),
					IF($(vMM_Avg_PercScore_CollegeCareer_3Year_Current)  < 0.75, rgb(0,176,80),
					IF($(vMM_Avg_PercScore_CollegeCareer_3Year_Current) >= 0.75, rgb(0,112,192)))));

	
	
	//// Table (bottom-left)
		/// Measure 1: College & Career - # of reports
			// The number of "College & Career" reports in the most recent three years.
			let vMM_Count_Reports_CollegeCareer_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Count(distinct {<[Points Possible in Domain] = {">0"}, [Domain Name] = {"College & Career"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearDomainKey),
					Count(distinct {<[Points Possible] = {">0"}, [Domain Name] = {"College & Career"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearKey)
				), '#,##0');
			let vLab_Count_Reports_CollegeCareer_3Year_Current = 'College & Career: # of School Reports';
			
		/// Measure 2: College & Career - Average Points Possible
			// The average number of total possible points for all available "College & Career" metrics in the previous three years. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PointsPossible_CollegeCareer_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Avg( {<[Domain Name] = {"College & Career"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Possible in Domain]),
					Avg(Aggr(Sum({<[Domain Name] = {"College & Career"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Possible]), %SchoolReportYearKey]))
				), '#0.#');
			let vLab_Avg_PointsPossible_CollegeCareer_3Year_Current = 'College & Career: Average # of Points Possible';

		/// Measure 3: College & Career - Average Points Earned
			// The average number of points earned for all available "College & Career" metrics in the previous three years. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PointsEarned_CollegeCareer_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Avg( {<[Domain Name] = {"College & Career"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Earned in Domain]),
					Avg(Aggr(Sum({<[Domain Name] = {"College & Career"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Points Earned]), %SchoolReportYearKey]))
				), '#0.#');
			let vLab_Avg_PointsEarned_CollegeCareer_3Year_Current = 'College & Career: Average # of Points Earned';

		/// Measure 3: College & Career - Average Score %
			// vMM_Avg_PercScore_CollegeCareer_3Year_Current 
			

		/// Measure 4: College & Career - Average Tier
			// The average tier for the "College & Career" achievement domain for the previous 3 years (< 0.25 = 'Intervene', < 0.50 = 'Watch', < .75 = 'Reinforce', >= 'Model'). Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_Tier_CollegeCareer_3Year_Current = 
				If($(vMM_Avg_PercScore_CollegeCareer_3Year_Current) < 0.25, 'Intervene',
					If($(vMM_Avg_PercScore_CollegeCareer_3Year_Current) < 0.5, 'Watch',
					If($(vMM_Avg_PercScore_CollegeCareer_3Year_Current) < 0.75, 'Reinforce',	
					If($(vMM_Avg_PercScore_CollegeCareer_3Year_Current) >= 0.75, 'Model')))	
				);
			let vLab_Avg_Tier_CollegeCareer_3Year_Current = 'College & Career: Average Tier';


		/// Measure 5: College & Career - # of reports in "model" or "reinforce"
			// The number of reports at the "Model" and "Reinforce" tier withing the "College & Career" domain.
			let vMM_Count_Reports_ModelReinforce_CollegeCareer_3Year_Current = Num(
				If($(vExpr_NoMetricSelected),
					Count(distinct {<[Tier in Domain] = {"Model", "Reinforce"}, [Domain Name] = {"College & Career"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearDomainKey),
					Count(distinct {<[Tier in Domain] = {"Model", "Reinforce"}, [Domain Name] = {"College & Career"}, IsSum = {0}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}%SchoolReportYearKey)
				), '#,##0');
			let vLab_Count_Reports_ModelReinforce_CollegeCareer_3Year_Current = 'College & Career: # of "Model" and "Reinforce" School Reports';
		
		
		/// Color
			let vCol_YearEnd = If(YearEnd = 2017, '#398635', If(YearEnd = 2016, '#737373', If(YearEnd = 2015, '#BDBDBD', '#F0F0F0')));


	//// Bar Chart (right)
		/// Title
			let vTitle_Avg_PercScore_CollegeCareer_Current = 'Average College & Career Score';

		/// SubTitle
			let vSubTitle_Avg_PercScore_CollegeCareer_Current = '';	

		/// Measure 1
			// The percent of possible points earned for all available "College & Career" metrics in the most current year. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PercScore_CollegeCareerToMetric_Current = Num(
				IF($(vExpr_MultipleMetricsSelected),
		        	Avg(Aggr(Sum({<IsSum={0}, [Domain Name]={"College & Career"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Earned]) / Sum({<IsSum={0}, [Domain Name]={"College & Career"}, YearEnd={$(=$(v_Max_YearEnd))}>}[Points Possible]), [%SchoolReportYearKey]))
		              ,
		            Avg({<YearEnd={$(=$(v_Max_YearEnd))}, [Domain Name]={"College & Career"}>}[Percent Earned in Domain])
		        )					
				, '#0.#%');
			
			let vLab_Avg_PercScore_CollegeCareerToMetric_Current = 
				IF($(vExpr_MultipleMetricsSelected),
		        	'Average Score in College & Career Domain ('& $(v_Max_Year) &')'
		              ,
		            'Average Score in College & Career Domain ('& $(v_Max_Year) &')'
		        );

		/// Color:
			let vCol_Avg_PercScore_CollegeCareerToMetric_Current = 
				IF($(vMM_Avg_PercScore_CollegeCareerToMetric_Current) < 0.25, rgb(192,80,77),
					IF($(vMM_Avg_PercScore_CollegeCareerToMetric_Current) < 0.5, rgb(247,150,70),
					IF($(vMM_Avg_PercScore_CollegeCareerToMetric_Current)  < 0.75, rgb(0,176,80),
					IF($(vMM_Avg_PercScore_CollegeCareerToMetric_Current) >= 0.75, rgb(0,112,192)))));

///// Educator Effectiveness Domain Sheet
	//// Line Graph (top-left) - shows last 3 years of performance in the College & Career domain, drill to metrics
		/// Title
			let vTitle_Avg_PercScore_EducatorEffectiveness_3Year_Current = 'Each Educator Effectiveness Score for Previous 3 Years';

		/// SubTitle
			let vSubTitle_Avg_PercScore_EducatorEffectiveness_3Year_Current = '';

		/// Measure 1
			// The average percent of possible points earned for all available "College & Career" metrics in the previous 3 years. Without selections this defaults to the domain level. If a single domain is selected this will display individual metrics.
			let vMM_Avg_PercScore_EducatorEffectiveness_3Year_Current = Num(
				Avg( {<[Domain Name] = {"Educator Effectiveness"}, YearEnd={">=$(=$(v_LastLast_YearEnd))"}>}[Percent Earned for Metric])
				, '#0%');

			let vLab_Avg_PercScore_EducatorEffectiveness_3Year_Current = 'Educator Effectiveness: Average Score';	
			
		/// Color
			let vCol_Avg_PercScore_EducatorEffectiveness_3Year_Current = 
				IF($(vMM_Avg_PercScore_EducatorEffectiveness_3Year_Current) < 0.25, rgb(192,80,77),
					IF($(vMM_Avg_PercScore_EducatorEffectiveness_3Year_Current) < 0.5, rgb(247,150,70),
					IF($(vMM_Avg_PercScore_EducatorEffectiveness_3Year_Current)  < 0.75, rgb(0,176,80),
					IF($(vMM_Avg_PercScore_EducatorEffectiveness_3Year_Current) >= 0.75, rgb(0,112,192)))));
	
///// Table Page

	//// Table
		/// Measure 1: City rank
			// Description:
			// City Rank for a selected school in the current year. If multiple metrics are selected, this is equal to overall score. If a selection on Domain is made this is equal to the score for the domain.
			let vMM_CityRank_OverallToDomain_Current = Num(
				IF ($(vExpr_AllDomainsPossible),
					Only({<YearEnd={$(=$(v_Max_YearEnd))}>}[City Rank Overall]),
				    IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
				    	Only({<YearEnd={$(=$(v_Max_YearEnd))}>}[City Rank in Domain])
				    )
				)
				, '#0');

			let vLab_CityRank_OverallToDomain_Current = 
				IF ($(vExpr_AllDomainsPossible),
					'Overall City Rank (' & $(v_Max_Year) & ')',
				    IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
				    	'City Rank in ' & GetFieldSelections([Domain Name]) & ' (' & $(v_Max_Year) & ')'
				    )
				);

			let vMM_CityRankPerc_OverallToDomain_Current = Num(
				IF ($(vExpr_AllDomainsPossible),
					Only({<YearEnd={$(=$(v_Max_YearEnd))}>}[City Rank Overall]) / Only({<YearEnd={$(=$(v_Max_YearEnd))}>}[Total Schools Eligible Overall]),
				    IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
				    	Only({<YearEnd={$(=$(v_Max_YearEnd))}>}[City Rank in Domain]) / Only({<YearEnd={$(=$(v_Max_YearEnd))}>}[Total Schools Eligible in Domain]) 
				    )
				)
				, '#0%');

			let vCol_CityRankPerc_OverallToDomain_Current = 
				IF($(vMM_CityRankPerc_OverallToDomain_Current) > 0.8, '#AE1C3E',  
				IF($(vMM_CityRankPerc_OverallToDomain_Current) > 0.6,'#ED875E',
				IF($(vMM_CityRankPerc_OverallToDomain_Current) > 0.4, '#F2D2AE',
				IF($(vMM_CityRankPerc_OverallToDomain_Current) > 0.2, '#5EA4D9',
				IF($(vMM_CityRankPerc_OverallToDomain_Current) <= 0.2, '#3C52A1')))));

		/// Measure 2: Peer rank
			// Description:
			// Peer Rank for a selected school in the current year. If multiple metrics are selected, this is equal to overall score. If a selection on Domain is made this is equal to the score for the domain.
			let vMM_PeerRank_OverallToDomain_Current = Num(
				IF ($(vExpr_AllDomainsPossible),
					Only({<YearEnd={$(=$(v_Max_YearEnd))}>}[Peer Rank Overall]),
				    IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
				    	Only({<YearEnd={$(=$(v_Max_YearEnd))}>}[Peer Rank in Domain])
				    )
				)
				, '#0');

			let vLab_PeerRank_OverallToDomain_Current = 
				IF ($(vExpr_AllDomainsPossible),
					'Overall Peer Rank (' & $(v_Max_Year) & ')',
				    IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
				    	'Peer Rank in ' & GetFieldSelections([Domain Name]) & ' (' & $(v_Max_Year) & ')'
				    )
				);

			let vMM_PeerRankPerc_OverallToDomain_Current = Num(
				IF ($(vExpr_AllDomainsPossible),
					Only({<YearEnd={$(=$(v_Max_YearEnd))}>}[Peer Rank Overall]) / Only({<YearEnd={$(=$(v_Max_YearEnd))}>}[Schools Eligible in Peer Group Overall]) ,
				    IF ($(vExpr_SingleDomainSelected_AllMetricsPossible),
				    	Only({<YearEnd={$(=$(v_Max_YearEnd))}>}[Peer Rank in Domain]) / Only({<YearEnd={$(=$(v_Max_YearEnd))}>}[Schools Eligible in Peer Group in Domain]) 
				    )
				)
				, '#0%');

			let vCol_PeerRankPerc_OverallToDomain_Current = 
				IF($(vMM_PeerRankPerc_OverallToDomain_Current) > 0.8, '#AE1C3E',  
				IF($(vMM_PeerRankPerc_OverallToDomain_Current) > 0.6,'#ED875E',
				IF($(vMM_PeerRankPerc_OverallToDomain_Current) > 0.4, '#F2D2AE',
				IF($(vMM_PeerRankPerc_OverallToDomain_Current) > 0.2, '#5EA4D9',
				IF($(vMM_PeerRankPerc_OverallToDomain_Current) <= 0.2, '#3C52A1')))));


		/// Colors for previously defined measures
			let vCol_Avg_PercScore_OverallToDomainToMetric_3Year_Current = 
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Current) < 0.25, 'rgb(192,80,77)',
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Current) < 0.5, 'rgb(247,150,70)',
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Current) < 0.75, 'rgb(0,176,80)',
				If($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_Current) >= 0.75, 'rgb(0,112,192)'))));

			let vCol_Avg_PercScore_OverallToDomainToMetric_3Year_YOY = 
				IF($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_YOY) <= -0.2, '#AE1C3E',
				IF($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_YOY) <= -0.1,'#ED875E',
				IF($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_YOY) < 0, '#F2D2AE',
				IF($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_YOY) < 0.1, '#D1EBFB',
				IF($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_YOY) < 0.2, '#5EA4D9',
				IF($(vMM_Avg_PercScore_OverallToDomainToMetric_3Year_YOY) >= 0.2, '#3C52A1'))))));

///// SPP Page
	
	//// Scatter Chart (center)

		/// Title
			let vTitle_Avg_PercScore_v_SPP = 'SPP - ' & FirstSortedValue(distinct [SPP Metric], [SPP Metric]) & ' (vertical) vs. SPR Score (horizontal)';

		/// SubTitle

		/// Measure 1
			let v_Format_SPP_Selected = If (FirstSortedValue(distinct [SPP Metric Is Percent], [SPP Metric]) = 1, '#0%', '##0');

			// The Penssylvania School Performance Profile (SPP) "Final Academic Score" for the current year. Please visit http://www.paschoolperformance.org for more information.
			let vMM_Avg_SPPScore_Selected_Current = Num(
				If (FirstSortedValue(distinct [SPP Metric Is Percent], [SPP Metric]) = 1,
					Avg({<[SPP Metric] = {"$(=FirstSortedValue(distinct [SPP Metric], [SPP Metric]))"}, [SPP Year] = {"$(=$(v_Max_Year))"}>}[SPP Score]) / 100
					,
					Avg({<[SPP Metric] = {"$(=FirstSortedValue(distinct [SPP Metric], [SPP Metric]))"}, [SPP Year] = {"$(=$(v_Max_Year))"}>}[SPP Score]) 
				) + 0.0001, '$(=$(v_Format_SPP_Selected))'
			);

			let vLab_Avg_SPPScore_Selected_Current = 'SPP - ' & FirstSortedValue(distinct [SPP Metric], [SPP Metric]) & ' (' & $(v_Max_Year) &')';

			// add 5% to max that is not a %
			let vYMax_Avg_SPPScore_Selected_Current = If (FirstSortedValue(distinct [SPP Metric Is Percent], [SPP Metric]) = 1, 
				1, 
				Max({<[SPP Metric] = {"$(=FirstSortedValue(distinct [SPP Metric], [SPP Metric]))"}, [SPP Year] = {"$(=$(v_Max_Year))"}>}[SPP Score]) + 0.05 * Max({<[SPP Metric] = {"$(=FirstSortedValue(distinct [SPP Metric], [SPP Metric]))"}, [SPP Year] = {"$(=$(v_Max_Year))"}>}[SPP Score]));

		/// We may not use the following, but we'll keep it in the system
			// The Penssylvania School Performance Profile (SPP) "Final Academic Score" for the current year. Please visit http://www.paschoolperformance.org for more information.
			let vMM_Avg_SPPScore_FinalAcademicScore_Current = Num(
				Avg({<[SPP Metric] = {"Final Academic Score"}, [SPP Year] = {"$(=$(v_Max_Year))"}>}[SPP Score]) / 100
				+ 0.0001, '#0%');

			let vLab_Avg_SPPScore_FinalAcademicScore_Current = 'Overall SPP Score' & ' (' & $(v_Max_Year) &')';